### ISSUE TITLE
Decide on Open Source Licence

### ISSUE THREAD

**Issue by cookeac** [adewg/ICAR#10]
Work through with the wider ADE working group the open source or creative commons licence to be used. Make use of https://opensource.org/licenses decision tree and/or https://creativecommons.org/choose/

**Comment by cookeac** [comment]
Key questions to help us decide:
1. Is what we are creating software+documentation (if yes, choose an **opensource.org** licence) or just documents and data (if this, choose a **creativecommons.org** licence)
2. May organisations create derivatives (and may these be for commercial use)? I suspect that organisations MAY need to create derivatives that extend the specification. If not, then we want a **No Derivatives** licence. 
3. If we do allow organisations to create derivatives, do we insist they must also be open source/creative commons? If so, then we want a **Share Alike** licence (viral open source).

**Comment by cookeac** [comment]
Suggested licence options as a table:

Licence | Designed for | Require attribution | Allow derivatives | Derivatives open too 
-------- | -------------- | --------------------- | ------------------ | ---------------------
Apache Licence 2.0 | Code (and its documentation) | Yes | Yes | No 
Code (GNU LGPLv3 | Code (and its documentation) | Yes | Yes | Yes 
CC Attribution 4.0 | Docs and data (no code) | Yes | Yes | Yes 
CC Attribution-NoDerivatives 4.0 | Docs and data (no code) | Yes | No | - 
CC Attribution-ShareAlike 4.0 | Docs and data (no code) | Yes | Yes | Yes

**Comment by cookeac** [comment]
On 17 January 2020 the Technical Group decided:
1. A software licence is appropriate because the specifications are edited and used like software. See also the OpenAPI specification licence, which is a software licence.
2. Attribution is required.
3. Protection for contributors is required.
4. Derivatives should be possible - for instance, national or species-specific recording schemes may extend the specification.
5. It is less possible to enforce a level of compliance with the specification. Because ICAR is an organisation and a trademark, ICAR could tackle organisations that claimed to be ICAR-compliant but were not. The licence should not attempt to do this.

For this reason we recommended the [Apache Licence 2.0](https://www.apache.org/licenses/LICENSE-2.0).

Next steps:
1. Contributors within the meeting on 17 January 2020 approved use of the licence and were willing for their contributions to be covered under this licence.
2. Animal Data Exchange Working Group to review the licence proposal.
3. ICAR management to review the licence proposal.
4. If approved by ADE and management, any remaining existing contributors need to agree to the licence covering their contributions before we publish.

**Comment by Jongmassey** [comment]
Apache 2 is good by me, is my usual go-to license

**Comment by cookeac** [comment]
All contributors have agreed to the Apache licence 2.0. I have loaded this as pull request #63
