### ISSUE TITLE
Date time format for UTC

### ISSUE THREAD

**Issue by MetroMarv** [adewg/ICAR#102]
In the `icarDateTimeType` and also in the example URLs we use the format `date-time` specified in the  [JSON schema specification](https://json-schema.org/understanding-json-schema/reference/string.html#dates-and-times) for date time properties.

As far as I remember from our discussions we always want to exchange UTC time stamps. So I'd assume that it's sufficient to just exchange the date and the time component and not the offset.

I didn't check possible ways to fix this, but I guess there is a way to define custom formats (I'll check this tomorrow). Or is that format intended?

**Comment by cookeac** [comment]
@MetroMarv great question and thanks for asking.
The intent, as per the JSON schema specification, is that implementers are specific about time zone. As you note, UTC is also intended, but to make this clear the "Z" suffix or "+00:00" SHOULD be used.

**Comment by cookeac** [comment]
Updated the Wiki with the comment
A note regarding *eventDateTime*: When specifying dates in icarEventResource and other ICAR entities, date times MUST specify time zone, and SHOULD generally use UTC (using the special "Z" designator as per IS8601 and W3C guidelines).
