### ISSUE TITLE
Cannot find information about ICAR_ValidSampleFillingIndicator code list

### ISSUE THREAD

**Issue by ghost** [adewg/ICAR#108]
During implementation of milk sampling information we came across this type:

[icarValidSampleFillingIndicatorType.json](https://github.com/adewg/ICAR/blob/ADE-1/enums/icarValidSampleFillingIndicatorType.json)

The enum values are just "0", "1" and "2" and the file references the "ICAR_ValidSampleFillingIndicatorCode list" which I couldn't find anywhere.

I'd propose to use more descriptive enum values in a future version of the standard (as this would be a breaking change). Unit then, putting information about the existing enum values into the description of the type would be very helpful.

**Comment by cookeac** [comment]
In the old ICAR XML documentation, the enumerated values mean
0 - successful milking (>80% of expected milk)
1 - incomplete (<20% expected milk) or interrupted
2 - complete, measurement not complete (between 20% and 80% of expected milk)

Without introducing a breaking change, the solution for 1.1 would be to document this in the description of the type.

**Comment by cookeac** [comment]
We decided we would do a short term fix by improving the description for the type (#116). For ADE-2 (breaking change) we will propose a more self-explanatory enumeration.
