### ISSUE TITLE
Quarter Milking Type Quarter Id Enum differs from ICAR Data Dictionary

### ISSUE THREAD

**Issue by ghost** [adewg/ICAR#112]
In Section 4.17 of the ICAR Data Dictionary:

https://www.icar.org/Guidelines/15-Appendix-A-Data-Dictionary.pdf

the quarter ids are listed as:
- LF Left front 
- RF Right front 
- LR Left rear 
- RR Right rear

However, the enum https://github.com/adewg/ICAR/blob/ADE-1/types/icarQuarterMilkingType.json lists:
- "LF",
- "RF",
- "LB",
- "RB"

Maybe one of the documents should be changed :)

**Comment by erwinspeybroeck** [comment]
I fear the data dictionary is correct - I don't know how these slipped into the ICAR proposal ...
