### ISSUE TITLE
gestations API

### ISSUE THREAD

**Issue by erwinspeybroeck** [adewg/ICAR#121]
MSD  (Merck Sharp & Dohme)  one of the biggest farmaceutical firms in the world, is already using some JoinData API's that uses CRV data as a source, without us (CRV) knowing. One of them is an API to retrieve gestations on a location - expected calving dates was what they were interested in.
We ICARized the JoinData API for use with our data exchange with Lely and discovered MSD was using this API too. We changed it as follows:

[
      {
        "animal": {
            "id": "string",
            "scheme": "nl-v1"
        },
        "sireIdentifiers": [
          {
              "id": "string",
              "scheme": "nl-v1"
          }
        ],
        "expectedCalvingDate": "2020-06-12T10:48:36.220Z",
        "isSexedSemen": true,
        "sexedGender": "Female",
        "inseminationType": "NaturalService"
      }
    ]
  }
]

**Comment by erwinspeybroeck** [comment]
This was discussed on the ICAR meeting from June, 19th.
The proposal was to limit the response to animal, sire and expected calving date

[
{
"animal": {
"id": "string",
"scheme": "nl-v1"
},
"sireIdentifiers": [
{
"id": "string",
"scheme": "nl-v1"
}
],
"expectedCalvingDate": "2020-06-12T10:48:36.220Z"
}
]
}
]

**Comment by cookeac** [comment]
Closing this now as implemented.
