### ISSUE TITLE
Collections for aggregrating datahubs

### ISSUE THREAD

**Issue by alamers** [adewg/ICAR#129]
As discussed in the working group just now, at CRV & JoinData we are looking at how we can best use collections.

At JoinData, we allow a consumer to query multiple sources at the same time; the consumer does not (necessarily) need to know which manufacturers or data sources are available at a specific farm. The way we do this is to delegate the original query to multiple sources and aggregate the results. In doing so, we would very much like to "not touch" the messages for multiple reasons:
- our mission scope is limited to transporting the data and not transforming it or reading/using it
- we envision use cases where these messages may actually be end-to-end encrypted
- we would like to avoid having knowledge of syntax of a standard, especially since there may be other standards in other branches/sectors: this would increase our technical effort but 

Currently we have a "JoinData enveloppe" around these messages, creating a collection the responses and indicating the original source.

If/when we want to support the collections, we would very much stay as much as possible within the ICAR standard. But we see a couple of issues; here we are trying to collect comments on how to proceed :) On one hand we can simply continue with a "JoinData enveloppe", on the other hand I expect there to be more aggregating parties and/or many-to-one/one-to-many communication protocols that will encounter similar issues. As such, it would be good to support it as a standard.

In the ICAR standard, we've been working with multiple layers: the message / resource layer (defined by json schema messages) and a transport layer (with a suggested url REST scheme). Note that these collections are somewhat in between these two layers: it describes a payload but also groups them together for easy transport. Pagination in collections is for example offered for specific types of consumption/transport where you have the requirement of short(er) messages.

Some of the issues that we are struggling with, and where we very much appreciate comments on:
- Not all data sources will support pagination; some of them simply limit the query that you can ask. Pagination thus will be different per source. 
- URL references have to be either relative, or we have to rewrite them, or they will be pointing directly to the source.
- combining collections into a single collections is not always obvious: some times these are disjunct devices and combining results is fine (as long as we can keep track of the original device); in other cases, e.g. herd lists, there may simply be multiple perspectives on the same truth.

So I guess, my questions are:
- do other parties have similar use cases (many-to-one / one-to-many channels)?
- where do we place collections in our 'stack' of standardization: is it a message by itself or is it a method of transport? 
- is offering an enveloppe combining ICAR-messages and ICAR-collections compliant with ICAR, or even with the ICAR recommended url scheme?
- other thoughts, ideas?

**Comment by ahokkonen** [comment]
@alamers 

In my opinion collections are closer to transportation layer rather that the standard messages.

I see collections as a service layer wrappers for messages providing additional meta information and pagination support for direct client-to-node interactions. 

In our solution collections should not be a problem, but I can see potential problems of combining/aggregating data from different sources is same call.

One of the solutions would be to define simple message array responses as part of url schema standard:

- adding both collection and array support for each endpoint controlled by query parameter (suggested be @erwinspeybroeck) - defining as oneOf/anyOf
- having multiple endpoints for each message types with different response types (could be messy)

I also see that using arrays over collection might be more easy/integration-friendly flow for many parties implementing standard for data exchange (at least at starting point).

**Comment by ghost** [comment]
I'd prefer the query parameter as this makes it rather simple looking at it from a technical side. Nevetherless, I see the drawback that communication partners need to ensure that the partners they integrate with understand and implement the parameter. If that's agreed, however, switching between the more "user friendly" and the more "machine friendly" ways of returning data is easy.

**Comment by erwinspeybroeck** [comment]
An extra use case for using the array solution instead of collections would be when using webhooks. When someone gets a notification that e.g. an animal with technical id x has been changed, one would do a GET on that id to retrieve the changed animal data.
A GETwith collections on the other hand could be interesting when retrieving "starting" information - somebody wants to start keeping data for a certain location, so they retrieve once all information, and from then on they would use the notification route.

**Comment by gra-moore** [comment]
I think this use case is very important and for data aggregators and for bulk data sharing between nodes in the agri sector. 

The current APIs are very single location focused and chatty. 

See the API published here as a pattern for keeping sets of data in sync with a simple dataset centric protocol: https://open.mimiro.io/specifications/uda/latest.html, these ideas are also now reflected in the norfor API with the datasets endpoints.
