### ISSUE TITLE
Medicine resource API

### ISSUE THREAD

**Issue by cookeac** [adewg/ICAR#135]
There may be value in having a medicine resource API (a minimal *icarMedicineResource* is defined but this could benefit from other properties, including withdrawal periods by species).

This would allow master lists of medicines to be shared:
* nationally; or
* by recording service for clients of that service; or
* by software packages for clients of that package.

What expectations would you have around such an API - would you use it? What would you expect to retrieve? What filter parameters would you expect?

**Comment by erwinspeybroeck** [comment]
Andrew, we have a medicine API in place - it uses data from the official licensing organistations in Belgium (FAGG) and the Netherlands  (FIDIN)

description: | a drug or other preparation for the treatment or prevention of disease
-- | --
id* | idstringThe technical, non-meaningful and unique identification code of an object.
licenseNumber | licenseNumberstringA medicine is licensed under this number. In the Netherlands this number is called the REG NL number, in Belgium this number is called the authorisation number.
type* | typestringMedicines of the type STANDARD are provided by the official organisations licensing medicines. Type CUSTOM is indicating the medicines that the customer has added as a substance he is using in his herd and are not part of the licensed medicines.
name | namestringName of the medicine. No enum - list of medicines is responsability of FAGG and FIDIN.
administrationRoute | administrationRoutestringThe route of administration of the medicineEnum:Array [ 12 ]
amountPerAdministration | amountPerAdministrationnumberThe amount of the medicine that has to be used for a treatment.
amountUnit | amountUnitstringThe unit in which the medicine is administeredEnum:Array [ 14 ]
waitingPeriodMeat | waitingPeriodnumberThe period in hours one has to wait after using the medicine to deliver milk or meat to the consumers
waitingPeriodMilk | waitingPeriodnumberThe period in hours one has to wait after using the medicine to deliver milk or meat to the consumers
