### ISSUE TITLE
do not breeds RESOURCE API

### ISSUE THREAD

**Issue by ozkank** [adewg/ICAR#138]
we need to define the content of do not breeds (keep-open)

path : /locations/{location-scheme}/{location-id}/do-not-breeds
this is the example scheme : 

`[
  {
    "id": "string",
    "animal": {
      "id": "string",
      "scheme": "string"
    },
    "eventDateTime": "2020-08-11T11:00:26.407Z",
    "location": {
      "id": "string",
      "scheme": "string"
    },
    "traitLabel": {
      "id": "string",
      "scheme": "string"
    },
    "responsible": "string",
    "contemporaryGroup": "string"
  }
]`

for details please ask Vincent from CRV or Ozkan, Namık from Lely.

**Comment by cookeac** [comment]
What would happen if the event **icarReproMatingRecommendationResource** had a "Keep Open" or "Do not Breed" flag (boolean)? The event could then identify animals which should not be bred OR the recommended sire(s) if the animals were to be bred.

**Comment by erwinspeybroeck** [comment]
But what if a farmer wants to report that he wants a cow to be not inseminated anymore. Then you would like to have an event/message that indicates that a cow is kept open. We discussed some time with Lely about the name : do-not-breed or keep-open. It can be used to avoid animals appear on attention list e.g. for inseminations, or for calving.

**Comment by cookeac** [comment]
At the meeting on 14 August 2020 we decided to create an event to indicate the farmer did not want to breed an animal.

We asked participants to please consider whether this should also be reflected in a flag on an animal, or membership of a set with a purpose of "do not breed".

**Comment by cookeac** [comment]
Fixed by #143

**Comment by cookeac** [comment]
Adding DoNotBreed to *reproductionStatus*
