### ISSUE TITLE
Animal Sets (groups) membership change events

### ISSUE THREAD

**Issue by cookeac** [adewg/ICAR#139]
After implementing **icarAnimalSetResource** (issues #88) we thought it would be useful to have events that could record the date at which an animal joined or entered a set, and left/was removed from a set.

As with our other events, these should probably be animal-oriented (events based on the Animal ID) and reference the set.
For example: 
* **icarSetArrivalEventResource** and
* **icarSetDepartureEventResource**

**Comment by ghost** [comment]
@MarvinGEA and I created a pull request that adds animalSetJoin and animalSetLeave events.

While implementing this we were wondering whether a "animalSetChangeEvent" would be more appropriate for some use cases. However, this event would then be the first one to not reference a single animal.
