### ISSUE TITLE
Add Animal Health Status to Animal Resource

### ISSUE THREAD

**Issue by ghost** [adewg/ICAR#148]
In issue #111 we discussed reproduction and lactation status values. In addition to this, a health status of an animal would also be very helpful. As possible values I'd like to propose:

- Healthy
- Suspicious
- Ill
- In Treatment
- To Be Culled

On the animal, this would be an additional field defining the current status. In addition to this, a Health Check Event could be added so that an observation of a changed health status can be filed.

I think, the Health Check Event could be a little bit more complicated because you might need diagnosis codes etc., however, if everyone is OK with the status field at the animal I could add the health status field already for the 1.1 release.

**Comment by cookeac** [comment]
There has already been a lot of work done on health diagnosis, which I think covers the coding mentioned above.

When we initially raised the prospect of a *Health Status*, there was recognition that some more work needed to be done to determine both an appropriate enumeration (the set above looks like a good start), and also to think about how that might interact with different systems. I think we need to have that discussion before including in ADE 1.1. What do others think?

Also:
* For me, in treatment and to be culled would typically be group (set) functions, and there might be several treatment groups.
* If I were after one key piece of health information for an animal, it would be the withdrawal status of the animal (to save me having to process through all the health treatments to see if the animal could be milked, sold, culled, etc).

**Comment by erwinspeybroeck** [comment]
We didn't have until now a use case for a health status of an animal, although it seems logical and consistent to have one.

Regarding the withdrawal status we created an API with which one can ask for the current status regarding withdrawal on a location:
GET /{market-country-code}/customer/{customer-id}/indications/waiting-periods
with a response
[
  {
    "animalId": scheme + id,
    "releaseMilkDateTime": "2020-09-02T05:55:17.114Z",
    "indicationMilk" : enum : colostrum, antibiotics
    "releaseMeatDateTime": "2020-09-02T05:55:17.114Z",
    "antibioticsTestNeeded": true,
    "numberOfAntibioticsTestsDone": 0,
    "latestAntibioticsTestResult": true
  }
]
This is based on specific conditions in the Netherlands and Belgium
In the Netherlands a farmer is obliged to withdraw milk during the first 3 days after calving
In Belgium a farmer needs, in case of antibiotics used in a treatment, at the end of the withdrawal period to perform a test on antibiotics, and only if that is showing a negative result he can release the milk.
Possibly there are other conditions in other countries ... I would be interested to know.

**Comment by ghost** [comment]
If we want to integrate this into the release, we should at least think about:
* do we need "icarHealthStatusObservedEventRessoure"?
* should the diagnosis event also get the same enum as a field? The diagnosis would then "imply" the new status of the animal after the event
* do we want other/more/less values?

**Comment by ghost** [comment]
@AndreasSchultzGEA can you please take this issue with you into one of the next meetings? Maybe someone can propose a better enum set for the values?

**Comment by AndreasSchultzGEA** [comment]
There is a PR prepared https://github.com/adewg/ICAR/pull/253/ which contains the ideas of this discussion.
Please review and provide information e.g. about the values of the health-status-values.

The withdrawal-topics should better be put into a separated issue.

**Comment by cvigorsICBF** [comment]
I mentioned the possibility of the status of  'Very Ill" on the call this morning that I thought I saw third party software using. I've had a quick look though the documentation, but I can't confirm that it is used. Therefore this suggestion can be ignored.
