### ISSUE TITLE
Define carcase data feedback event and collection

### ISSUE THREAD

**Issue by cookeac** [adewg/ICAR#155]
A farm may receive feedback from processors about animals that have been slaughtered and processed. A carcase event may have a number of fields identifying the plant and processing chain, the lot or group of animals, standard characteristics such as body weight and carcase weight.

Carcases of some species (notably cattle) are split and characteristics may be recorded for each side.

There may be some country-specific or scheme-specific records:
- carecase grades (EUROP, MSA, USDA)
- health or post-mortem results (ideally these should be standardised, but that may be unlikely).

**Comment by alamers** [comment]
In the Netherlands there is a standard for slaughter messages, recently it has been updated for pigs as well. I'll dig up some information.

**Comment by erwinspeybroeck** [comment]
Proposed in the JoinData interface:

[icarSlaughterType {
	description: Gives information about an animal 's slaughter.

	identifier * animalIdentifier {
		...
	}
	slaughterHouseIdentifier * companyIdentifier {
		...
	}
	slaughterHouseBranche string
	Branche number of the slaughterhouse,
	could be either GLN or UBN

	earTagNumber * string
	The ear tag number

	birth * icarDateTypestring($date)
	udt: DateType | A day of the month or year as specified by a number.

	dateTimeSlaughter * icarDateTypestring($date)
	udt: DateType | A day of the month or year as specified by a number.

	dateTimeInspection * icarDateTypestring($date)
	udt: DateType | A day of the month or year as specified by a number.

	weightSlaughtered * {
		value * number($double)
		multipleOf: 0.1
		unitCode * string
		UN / CEFACT Common Code
		for Units of Measurement.

		Enum: [KGM]
	}
	weightRejected * {
		value * number($double)
		multipleOf: 0.1
		unitCode * string
		UN / CEFACT Common Code
		for Units of Measurement.

		Enum: [KGM]
	}
	weightCorrection {
		value * number($double)
		multipleOf: 0.1
		unitCode * string
		UN / CEFACT Common Code
		for Units of Measurement.

		Enum: [KGM]
	}
	weightHookLeft {
		value * number($double)
		multipleOf: 0.1
		unitCode * string
		UN / CEFACT Common Code
		for Units of Measurement.

		Enum: [KGM]
	}
	weightHookRight {
		value * number($double)
		multipleOf: 0.1
		unitCode * string
		UN / CEFACT Common Code
		for Units of Measurement.

		Enum: [KGM]
	}
	animalClassification string
	Enum: [A0, B0, B1, C0, D0, D1, D2, D3, D4, E0, E1, E2, V0, Z0]
	gender * icarGenderCodeTypestring
	Based upon Icar gc: GenderCodeType.Allowed values are - F -
		for female and - M -
		for male.

	Enum: [F, M]
	classifier string
	fatCover * string
	Enum: [1, 2, 3, 4, 5]
	fatCoverSubdivision * string
	Enum: [+, o, -]
	conformation * string
	Enum: [S, E, U, R, O, P]
	conformationSubdivision * string
	Enum: [+, o, -]
	colorScore string
	Enum: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
	hairColorCode * {
		countryCode string
		Enum: [NL, BE]
		hairColor string
		Enum: [AR, AZ, BB, BR, BZ, DK, EB, EG, ER, EW, EZ, MR, MZ, OV, RB, RW, VB, ZB, ZW]
	}
	farmRegistrations[string Enum: [VUIL, TRAAG, MAGER, KREUPEL, ONTSTEKING, KNIE(L)]]
	kdsRegistrations[string Enum: [NIEREN, PAT_KNIE, PAT_STOMPBIL, PAT_FLANKEN, FEC_LONGEN, FEC_HART]]
	veterinaryPracticeNumber string
	contactDetails {
		contactType string
		Enum: [T, S]
		contactPerson string
	}
}]

**Comment by cookeac** [comment]
Reopening this event which the bot had helpfully closed!

**Comment by cookeac** [comment]
Noted need for pH, health and disease observations (e.g. fluke).
Clarity needed on weightCorrected.
Conformation grades - need to support international grading as well as EUROP.

**Comment by cvigorsICBF** [comment]
Some details on what could be available
**Liver Values:**
1 =  Normal
2A = Limited fluke damage
2B = Extensive fluke damage
3A = Live fluke limited
3B = Live fluke extensive
4 = Other
5 = Abscess 

A carcass can have more than one.

**Lung Values**
1 = Normal
2 = Limited Pneumonia
3 = Extensive Pneumonia
4 = Other

**Base Price** 
Price per kg (taxes included)

**Spec Price**
Final price per kg paid to the seller, after deductions and bonus

**Number of Residencies / Movements**
Perhaps this is not used in many countries?

**PH**
Decimal, e.g. 6.5

**Category of the Animal**
examples: BULL | COW | HEIFER | STEER | YBULL

**Seller's Membership of Quality Programmes**
Some farmers would be members of QA and other programmes with incentives to produce beef to particular criteria.

**Comment by cookeac** [comment]
There is quite a lot to these carcass observations, and many of the identifiers and measures are country- or region-specific.
We (@donwilson-rezare and I) have proposed a set of types and resources that we think represents most things.
We have some questions about how many observations should be in a single animal carcass observation event (all, or just observations on the same side, or at the same point in the chain?). We have gone for the latter.

We have proposed:
* Consignment extensions #359 
* Processing lots #360 
* Carcass resource or type #361 
* Generalised carcass observation #362 
* Animal carcass observations event #363 

We welcome your feedback and suggestions. Thanks @erwinspeybroeck and @cvigorsICBF for the sample data you have supplied.
