### ISSUE TITLE
Versioning and branches

### ISSUE THREAD

**Issue by alamers** [adewg/ICAR#163]
I noticed that all our documentation refers to the ADE-1 branch, e.g. https://editor.swagger.io/?url=https://raw.githubusercontent.com/adewg/ICAR/ADE-1/url-schemes/exampleUrlScheme.json is used a lot to quickly show off the API :) The latest and greatest version however is in ADE-1-1. 

ADE-1-1 has its own branch right now and ADE-1 is now outdated. Should ADE-1-1 be merged into ADE-1? The tags are already placed so we can retrieve 1.0.0, 1.1.0 and 1.1.1, etc.   

Also: I can't seem to find any documentation on our wiki on the versioning. We've discussed this in https://github.com/adewg/ICAR/issues/17 and there are some branch/tag policies in there. 

I propose the following:
* merge ADE-1-1 into ADE-1 branch
* delete the ADE-1-1 branch (no longer needed)
* document the versioning and branching strategies on the wiki based on issue 17. (If above is agreed to, I could do that)

**Comment by ahokkonen** [comment]
as I recall from our previous discussions that we'll be having a separate version branches only for the major versions (aka v1.x.x, 2.x.x). So I agree with @alamers that we need to merge ADE-1-1 to ADE-1 and remove 1-1.

**Comment by cookeac** [comment]
This suits me. I knew we had proposed a new branch for major (breaking change) versions, but thought we had later revised this in a meeting to minor versions too, at request from one of the participants. However, when I went back to the meeting minutes, I couldn't find it.

**Comment by cookeac** [comment]
Merged ADE-1-1 into ADE-1, made ADE-1 the default branch again and removed ADE-1-1
