### ISSUE TITLE
Activity and rumination data 

### ISSUE THREAD

**Issue by dirbSEGES** [adewg/ICAR#166]
Hi, 

Have there been any discussion about a ressource for receiving activity and rumination data through iDDEN?

**Comment by erwinspeybroeck** [comment]
Not yet, I guess, we are using with SCR an API by JoinData for activities, but only for SenseTime


icarHeatActivityVendorSpecific{description:Contains vendor specific fields. Only one vendor element can be present.scrSenseTimeicarHeatActivityScrSenseTime{description:Contains SenseTime specific fields. Only one element can be present per item.heatBehaviornumber($double)The behavior of the cow as it relates to it being in heat.dailyRuminationnumber($double)The number of minutes a cow ruminates during the day (24-hour period)dailyEatingnumber($double)The number of minutes a cow eats during the day (24 hour period)activityTrendnumber($double)The trend of the cow’s activity. This is usually higher when the cow is approaching the time it is in heat.}} | description: | Contains vendor specific fields. Only one vendor element can be present. | scrSenseTime | icarHeatActivityScrSenseTime{description:Contains SenseTime specific fields. Only one element can be present per item.heatBehaviornumber($double)The behavior of the cow as it relates to it being in heat.dailyRuminationnumber($double)The number of minutes a cow ruminates during the day (24-hour period)dailyEatingnumber($double)The number of minutes a cow eats during the day (24 hour period)activityTrendnumber($double)The trend of the cow’s activity. This is usually higher when the cow is approaching the time it is in heat.} | description: | Contains SenseTime specific fields. Only one element can be present per item. | heatBehavior | number($double)The behavior of the cow as it relates to it being in heat. | dailyRumination | number($double)The number of minutes a cow ruminates during the day (24-hour period) | dailyEating | number($double)The number of minutes a cow eats during the day (24 hour period) | activityTrend | number($double)The trend of the cow’s activity. This is usually higher when the cow is approaching the time it is in heat.
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
description: | Contains vendor specific fields. Only one vendor element can be present.
scrSenseTime | icarHeatActivityScrSenseTime{description:Contains SenseTime specific fields. Only one element can be present per item.heatBehaviornumber($double)The behavior of the cow as it relates to it being in heat.dailyRuminationnumber($double)The number of minutes a cow ruminates during the day (24-hour period)dailyEatingnumber($double)The number of minutes a cow eats during the day (24 hour period)activityTrendnumber($double)The trend of the cow’s activity. This is usually higher when the cow is approaching the time it is in heat.} | description: | Contains SenseTime specific fields. Only one element can be present per item. | heatBehavior | number($double)The behavior of the cow as it relates to it being in heat. | dailyRumination | number($double)The number of minutes a cow ruminates during the day (24-hour period) | dailyEating | number($double)The number of minutes a cow eats during the day (24 hour period) | activityTrend | number($double)The trend of the cow’s activity. This is usually higher when the cow is approaching the time it is in heat.
description: | Contains SenseTime specific fields. Only one element can be present per item.
heatBehavior | number($double)The behavior of the cow as it relates to it being in heat.
dailyRumination | number($double)The number of minutes a cow ruminates during the day (24-hour period)
dailyEating | number($double)The number of minutes a cow eats during the day (24 hour period)
activityTrend | number($double)The trend of the cow’s activity. This is usually higher when the cow is approaching the time it is in heat.

**Comment by erwinspeybroeck** [comment]
Maybe this can be a startign point for defining a standard on this

**Comment by dirbSEGES** [comment]
This could be great. Is SenseTime going to use iDDEN for exchanging data?

**Comment by ahokkonen** [comment]
@dirbSEGES iDDEN is just one of the system implementing ICAR ADE standard for data exchange. I guess this question should be addressed to iDDEN as well as to SenseTime
