### ISSUE TITLE
Definition for breed identifier scheme

### ISSUE THREAD

**Issue by ahokkonen** [adewg/ICAR#168]
Should some of the commonly used breed standards be defined in the ADE standard schemas?
Like ones used in interbull https://interbull.org/ib/icarbreedcodes ?

**Comment by cookeac** [comment]
Some time ago we compiled a list using the interbull codes, other ICAR references, and then more international breeds. It is far from complete (there are several hundred for some species). That list is on the [DataLinker web site](https://github.com/Datalinker-Org/Farm-Data-Standards/blob/master/Additional%20Value%20Lists/FarmDataStandards_Animal-Breed-List.md) at present.

**Comment by ahokkonen** [comment]
Is it so that ADE group is looking for combining all possible cattle breeds under one schema? 
For our cases we need to work only with a breeds within the integrated systems - so we need to define country/organization specific breed sets for each case

**Comment by cookeac** [comment]
*icarBreedIdentifierType* is an identifier with a scheme and id as you have noted, this makes it possible to define and use country-, organisation-, or application-specific schemes if required.

However, the ICAR Guidelines already define a set of breed codes (as also noted above), so we could define a scheme to identify these. Encouraging implementers to use the ICAR standard codes will enhance interoperability overall. However as noted, that list is incomplete and there would benefit in ICAR maintaining a more complete list. Is this something we should take up with the wider ADE working group?

**Comment by cookeac** [comment]
See also dynamic queries of lists in #109
