### ISSUE TITLE
Missing codes for MilkCharacteristicsType

### ISSUE THREAD

**Issue by dirbSEGES** [adewg/ICAR#170]
Hi, 

From Seges side we are missing these code in MilkCharacteristics: 

Udderpositions used for each QuarterMilkingType used to calculate breedingvalues for udder: 
"ZPOSITION" 
"XPOSITION"
"YPOSITION" 

And also these codes are missing: 
 
"TEMPERATURE" (milk temperature in °C or °F)
"YIELDDAY" (Average yield last 24 hour i KGM)
"AVGYIELDWEEK" (Average yield last 7 days) 

BR

**Comment by erwinspeybroeck** [comment]
It is always possible to add certain attributes to a response.
We have with Lely agreed upon adding the teat coordinates in an extended milking visit message. We could add this into the standard.

Temperature could be an extra characteristic

averages to my opinion should not be added in a milking visit event, but migth be part of another event

**Comment by dirbSEGES** [comment]
It would be great if the coordinates and temperature are added to the standards. 

I won't disagree with you about the averages.

**Comment by erwinspeybroeck** [comment]
Example of how the positions are in the response right now - would that be ok?
   
         "icarQuarterId": "LR",
            "xposition": 64,
            "yposition": 972,
            "zposition": 547,
            "quarterMilkingDuration": {
              "unitCode": "SEC",
              "value": 243
            },
            "quarterMilkingWeight": {
              "unitCode": "KGM",
              "value": 3.9
            },

**Comment by dirbSEGES** [comment]
Yes, it is okay.

**Comment by cookeac** [comment]
Agreed that Temperature should be added. We can add X, Y, Z positions as nullable because not all providers may wish to provide these. Average yields will be a separate API.
