### ISSUE TITLE
feedIntake in milkVisitEvent

### ISSUE THREAD

**Issue by dirbSEGES** [adewg/ICAR#171]
Hi, 

Could feedIntake be added in milkVisitEvent. I´m thinking the feedconsumption related to a milkVisitEvent. (when concentrate is given in parlour or AMS)  

I can see there is a discussion in issue #93  about the description.

**Comment by cookeac** [comment]
Our preference so far has been to keep the events separate - which would not stop in-parlour milking equipment sending both the milking visit and the feed intake event for an animal. This does raise a question whether there should be some way of linking simultaneous or related events by reference.

**Comment by erwinspeybroeck** [comment]
This would mean that in the feed intake event we have to include a reference to a milking event, probably by the unique id of that event

**Comment by dirbSEGES** [comment]
it is fair solution. Mayby include reference to Feedintake in MilkVisit?

**Comment by ahokkonen** [comment]
Would separate resources be a better solution for linking FeedIntake and MilkingVisit?
Some sort of FeedIntakeAndMilkingVisitLinkResource where you can set explicitly link between feed intake and milking visit? Is many-to-many connection needed?

**Comment by ghost** [comment]
I think having a sperate resource is a good idea. The main question for me is whether we need it in the upcoming release. Nevertheless, the linking resource is simple enough so we could just add it (with the overhead of creating the examples, collecitons, etc...).

Background: Chicken and egg problem: does the milkvisit come first or the feedvisit. With a separate resource you don't have to decide, you just add it after both happened. And the place where the decision that these two events belong together is made is independent of the event creation.

**Comment by cookeac** [comment]
@cookeac  to suggest semantics from another standards group that might be relevant.

**Comment by cookeac** [comment]
A generalised solution is described in #248
