### ISSUE TITLE
Feed Categories or Types

### ISSUE THREAD

**Issue by cookeac** [adewg/ICAR#172]
I've been looking for a set of feed types or categories (not individual feed names) that we could use for the feed types enumeration mentioned in #93.

* https://www.feedipedia.org/content/feeds has a set of categories, but these relate to the type of plant (or other source) used to generate the feed. In their example, maize grain and maize green forage would be in the same category. 

* In 1980 the International Network of Feed Information Centers (INFIC or IFN, coordinated by USAID) put together a [Feedbase specification](https://pdf.usaid.gov/pdf_docs/PNAAP782.pdf) for which there is an old PDF online (*Harris et al*). Their feed classes were:
* * Dry forages and roughages
* * Pasture, range plants or forages fed green
* * Silages
* * Energy feeds (grains, fruit)
* * Protein supplements
* * Mineral supplements
* * Vitamins
* * Additives

They also define a vast amount of feed attributes (properties). A number of later papers and articles 

* ICAR has a Feed and Gas working group https://www.icar.org/index.php/technical-bodies/working-groups/working-groupsfeed-and-gas/ but all the papers I have found standardise inputs to a Dry Matter equivalent, without discussing coding or representation of different feed types.

* The [Bar Diamond (USA) Feed Classification **System](http://bardiamond.com/Library/Feeds/Articles/BarDiamondFeedClassificationSystem.pdf) uses the 8 IFN classes above, plus another based on *Roughage, Concentrate, Supplement*, and another to designate *Nitrogenous, Fibrous, Lipid, Mineralized, Carbohydrate*. Finally they identify whether the protein source is mainly *Animal, Milk, Plant, Microbial, Non-protein Nitrogen, Fecal, or Mixed*.

* The Finnish feed tables at https://portal.mtt.fi/portal/page/portal/Rehutaulukot/feed_tables_english/feed_tables/ruminants use a *Group* including:
* * Cakes and meals
* * Feeds of animal origin
* * Fresh forages and pasture
* * Grains and seeds
* * Grass silages
* * Other silages
* * Hay and artificially dried grasses
* * Minerals
* * Plant by-products
* * Roots, tubers, fruits, and cabbages
* * Straw

* NZ Farm Data Standards have a [two-level categorisation system](https://github.com/Datalinker-Org/Farm-Data-Standards/blob/master/Pasture%20Graze%20and%20Feed/PGFDS_Lists-of-Valid-Values.md#Feed-Type), of which the top level is most helpful:
* * Grains
* * Straws
* * Green feeds
* * Processed
* * Silage
* * Vegetable and fruit
* * Hay

* DairyOne (USA) uses the following categories for [labs and analytics](https://dairyone.com/services/forage-laboratory-services/feed-composition-library/interactive-feed-composition-libraries/):
* * Forages, fresh
* * Forages, hay
* * Forages, silage
* * Grains and by-products, dry
* * Grains and by-products, high moisture or wet
* * Protein feeds, dry
* * Protein feeds, high moisture or wet

**Comment by cookeac** [comment]
FAO also has a list of "feed materials for ruminant species" (see http://www.fao.org/fileadmin/user_upload/gleam/docs/GLEAM_2.0_Model_description.pdf) table 3.2.
There are 30 items:

Number Material Description
Roughages
1 GRASSF Any type of natural or cultivated fresh grass grazed or fed to the animals.
2 GRASSH Hay (grass is cut, dried and stored) or silage (grass is cut and fermented) from any natural or cultivated grass.
3 GRASSH2 Hay from adjacent areas.
4 GRASSLEGF Fresh mixture of any type of grass and leguminous plants that is fed to the animals.
5 GRASSLEGH Hay or silage produced from a mixture of any type of grass and leguminous plants.
6 ALFALFAH Hay or silage from alfalfa (Medicago sativa)
7 GRAINSIL Silage from whole barley (Hordeum vulgare), oat (Avena sativa), buckwheat (Fagopyrum esculentum) and
fonio (Digitaria spp.) plants.
8 MAIZESIL Silage from whole maize (Zea mays) plants.
9 RSTRAW Fibrous residual plant material such as straw, brans, leaves, etc. from rice (Oryza spp.) cultivation.
10 WSTRAW Fibrous residual plant material such as straw, brans, leaves, etc. from wheat (Triticum spp.) cultivation.
11 BSTRAW Fibrous residual plant material such as straw, brans, leaves, etc. from barley (Hordeum vulgare), rye (Secale
cereale) or oat (Avena sativa) cultivation.
12 ZSTOVER Fibrous residual plant material such as straw, brans, leaves, etc. from maize (Zea mays) cultivation.
13 MSTOVER Fibrous residual plant material such as straw, brans, leaves, etc. from millet (Pennisetum glaucum, Eleusine
coracana, Panicum miliaceum, etc) cultivation.
14 SSTOVER Fibrous residual plant material such as straw, brans, leaves, etc. from sorghum (Sorghum spp.) cultivation.
15 TOPS Top portion of sugarcane (Saccharum spp.) plants, consisting of green leaves, bundle sheath and variable
proportions of immature cane.
16 LEAVES Leaves from natural, uncultivated vegetation found in trees, forest, lanes etc.
17 FDDRBEET Fodder beet (Beta vulgaris), also known as mangel beet or field beet, used as animal feed.
Cereals
18 GRAINS Grains from barley (Hordeum vulgare), oat (Avena sativa), buckwheat (Fagopyrum esculentum) and fonio
(Digitaria spp.).
19 CORN Grains from maize (Zea mays) plant.
By-products
20 MLSOY By-product from soy (Glycine max) oil production, commonly referred to as ‘soy cakes’ or ‘soybean meal’.
21 MLRAPE By-product from rape (Brassica napus) oil production, commonly referred to as ‘rape cakes’ or ‘rapeseed
meal’.
22 MLCTTN By-product from cottonseed (Gossypium spp.) oil production, commonly referred to as ‘cottonseed meal’.
23 PKEXP By-products from the production of kernel palm oil (Elaeis guineensis), commonly referred to as 'kernel cake'.
24 MZGLTM By-product from maize processing. It is a protein-rich feed, with about 65% crude protein content.
25 MZGLTF By-product from maize processing. Unlike the gluten meal, its protein content is lower, of about 25% crude
protein content.
26 BPULP Also known as ‘beet pulp’, is the remaining material after the juice extraction for sugar production from the
sugar beet (Beta vulgaris).
27 MOLASSES By-product from the sugarcane sugar extraction.
28 GRNBYDRY ‘Dry’ by-products of grain industries such as brans, middlings, etc.
29 GRNBYWET ‘Wet’ by-products of grain industries such as biofuels, distilleries, breweries, etc.
Concentrates
30 CONC Concentrate feed from feed mills.

**Comment by erwinspeybroeck** [comment]
Feed type : Enum --> ? feed distribution type, feed group type, feed class type, feed category
concentrate 
pasture/roughage
additives/supplements
other
extra text field what exactly (optional) -> the 30 codes above as a code list recommendation
--> ? add a scheme : in this case e.g. org.fao
link the code fao to the enum - hinking as disturbution, thinking as energy value-broad types - if the same then the naming of the enum is not that important

**Comment by erwinspeybroeck** [comment]
This issue is solved in the next release, definitions are added to develop
