### ISSUE TITLE
Feed Attributes or Properties

### ISSUE THREAD

**Issue by cookeac** [adewg/ICAR#173]
Suggesting work in this area to provide an initial, extensible code list in support of #93.
An alternative would be to allow for a Scheme + ID method of defining codes.

Common attributes seem to be:
| Analysis | Units | Meaning |
| ------ | ----- | ------- |
| Dry Matter (DM) | % (of feed) |  |
| Crude protein | % (of DM) | in NL/BE : RE (ruw eiwitgehalte) |
| Crude fibre | % (of DM) |  |
| NDF | % (of DM) | Neutral detergent fibre |
| ADF | % (of DM) | Acid detergent fibre |
| Lignin | % (of DM) |  |
| Ether extract | % (of DM) |  |
| Ash | % (of DM) |  |
| Starch | % (of DM) |  in NL/BE : ZET (zetmeel)|
| Total Sugars | % (of DM) |  |
| Gross Energy | MJ/kg DM |  |
| Digestable Energy (DE) | MJ/kg DM | Ruminants, same name but different values for monogastrics | 
| Metabolisable Energy (ME) | MJ/kg DM | Ruminants, same name but different values for monogastrics |

| Minerals| Units | Meaning |
| ------ | ----- | ------- |
| Calcium | g/kg DM | |
| Phosphorus | g/kg DM | |
| Potassium | g/kg DM | |
| Sodium | g/kg DM | |
| Magnesium | g/kg DM | |
| Manganese | mg/kg DM | |
| Zinc | mg/kg DM | |
| Copper | mg/kg DM | |
| Iron | mg/kg DM | |
| Aluminium | mg/kg DM | |

There are a bunch more around amino acids, tannins, nitrogen degradability.

**Comment by erwinspeybroeck** [comment]
There are formula's used to calculate a number of the feed properties out of feed properties that are analysed:

GE (gross energy) (kJ/kg) = 24,14 x RE + 36,57 x RVET + 20,92 x RC + 16,99 x OK - 0,63 x SUI*
* correction for sugar only when more than 80 g sugar per kg dry matter
RE = crude protein, RVET = crude fat, RC = crude fibre, SUI = sugar, OK(h) = 1000 – (liquid+ RAS (crude ashes) + RE + RVET(h) +RC) = other carbohydrates

ME (MJ/kg DM) = 14,94 VOS + 18,98 RVET –1,478 RC – 0,97 SUI  (VOS=Digestible organic matter)
q = 100 ME /GE

NElac = 0,6 x (1 + 0,004 x (q-57)) x 0,9752 x ME (in kJ/kg)
This is the net energy value for milk production

VEM = NElac / 6900 x 1000
VEM is a relative energy measure, using barley as a reference raw material.
One kg of air-dried barley with a certain (standardized) composition has an average net energy value for milk production (NElac) of 6900 kJ.
VEM = 0,6 x (1+0,004 x (q-57)) x 0,9752 x ME / 6,90 = (0,0003392 x q + 0,0654656) x ME with ME the above metabolizing energy and q
VEM is used for milk production - there is also a VEVI for meat production

Regarding the analysis there are mostly regulations or ISO specifications , e.g. for crude fibre : EC Regulation 152/2009;
ISO 6865, 2000

In NL/BE a system called DVE/OEB is used.
DVE = digestible protein (is also calculated from a number of properties)
OEB = Unstable Protein Balance = OEB = {RE x (1 - 1,11 x %BRE/100)} - {FOS x 0,150}
%BRE = rumen resistance of crude protein , FOS = rumen fermentable organic matter

My conclusion is that we need to have the possibility to add "local" feed properties. A number of feed properties will be common, I guess

**Comment by erwinspeybroeck** [comment]
add a field : calculated/measured to each attribute

schemes would be helpful, but might become complex for processing it --> use an icar scheme and try to pose it as a standard

**Comment by SvenSchierenbeck** [comment]
some more minerals:
| minerals        |units         |
| ------------- | ---------  |
| sulphur         | g/kg DM  |
| chlorine        | g/kg DM  |
| cobalt| mg/kg DM  |
|selenium|mg/kg DM|
|iodine|mg/kg DM|
|molybdenum|mg/kg GM|


As Andrew mentioned there are several vitamins and amino acids which could be added later. 
There are also some parameters of the German system and several parameters of the US CNCPS system missing. I will add some of them in the next days. I agree with Erwin that we should have the possibility to add some national feed properties.

**Comment by erwinspeybroeck** [comment]
This issue is solved in the next release, definitions are added to develop

**Comment by erwinspeybroeck** [comment]
This issue is solved in the next release, definitions are added to develop
