### ISSUE TITLE
Rank field in icarReproInseminationEventResource event

### ISSUE THREAD

**Issue by ahokkonen** [adewg/ICAR#180]
During standard implementation we've noticed that "Rank" field is missing from insemination event message.

Rank (the rank of intervention of each AI carried out within the same reproductive cycle) is the one field defined as recommended in ICAR general [rules ](https://www.icar.org/Guidelines/01-General-Rules.pdf)(2.4.4.10)

Technically this field could be calculated on server side, but in some cases there might be a need for providing it from the client.
Any obstacles for adding this new field to the icarReproInseminationEventResource message?

**Comment by ahokkonen** [comment]
Rank field is now part of icarReproInseminationEventResource message after my PR was merged.
For most cases Rank value is increased by 1 with each new AI during same reproductive cycle, **also in case of double insemination**.

**Comment by cookeac** [comment]
Fixed in #186
