### ISSUE TITLE
Define enumeration for icarReproParturitionEventResource - calvingEase

### ISSUE THREAD

**Issue by cookeac** [adewg/ICAR#185]
Currently the **calvingEase** attribute of *icarReproParturitionEventResource.json* is a string field with no definition.
There would be benefit in a consistent enumeration or score.

Splitting this issue out from the remaining discussion in #183 so that it can be addressed specifically. This will allow further research into the other topics in that issue.

**Research: Would this cause a breaking change for current implementations?**

**Comment by cookeac** [comment]
The ICAR Interbeef Technical Manual (2015/09) defines the following 1-5 scale for calving ease:
| Score | Meaning |
| ------ | ---------- |
| 1 | Easy, calved without assistance |
| 2 | Easy, calved with assistance |
| 3 | Difficult, extra or mechanical assistance |
| 4 | Difficult, veterinary assistance required |
| 5 | Caesarean or surgery |

The ICAR Dairy recording guidelines emphasise the importance of calving ease but do not provide a list.
A "Trait Atlas" guide quotes an unspecified ICAR guideline with the following:
| Score | Meaning |
| ------ | ---------- |
| 1 | Easy, calved without assistance |
| 2 | Easy, calved with some assistance |
| 3 | Difficult, hard pulling, assistance by 2 or more persons, mechanical assistance |
| 4 | Caesarean section  |
| 5 | Embryotomy |

The list in #183 is broadly compatible with the Interbeef list
| Score | Meaning |
| ------ | ---------- |
|   | Easy, without help |
|   | Easy, with help |
|   | Difficult, without veterinary care |
|   | Difficult, with veterinary care  |
|   | Caesarean section |

IF we are to define an enumeration, I recommend the five value list from Interbeef with the possible addition of Embryotomy (removal of a dead progeny) - although this could be represented in dairy cows with Caesarean and setting the liveProgeny and totalProgeny to indicate there is a stillborn progeny.

**Comment by cookeac** [comment]
After our discussions today, I propose the following enumeration for **calvingEase"" (by the way, this should really be parturitionEase or birthEase to cater for other species, but too late now!):

  "type": "string",

  "enum": [
    "1-EasyUnassisted",
    "2-EasyAssisted",
    "3-DifficultExtraAssistance",
    "4-DifficultVeterinaryCare",
    "5-CaesareanOrSurgery"
  ]

**Comment by ahokkonen** [comment]
@cookeac I guess we don't need number prefix in values? (aka 1-EasyUnassisted -> EasyUnassisted)

**Comment by cookeac** [comment]
The number prefixes were for alignment with the Interbeef and other standards which document meaning but use numeric values. I would rather not have the number prefixes, but then additional documentation will be needed.

**Comment by ahokkonen** [comment]
> The number prefixes were for alignment with the Interbeef and other standards which document meaning but use numeric values. I would rather not have the number prefixes, but then additional documentation will be needed.

It is better to have same naming convention for all enumeration values, I would prefer to have an additional documentation instead of prefixes :)
