### ISSUE TITLE
Move/rename locations.md

### ISSUE THREAD

**Issue by alamers** [adewg/ICAR#188]
As discussed in today's call, the `locations.md` file is not a proper name anymore since it contains all kinds of id- and enum-schemes these days. 

Also, by having it in the source repository it is harder to edit by non-technical people. 
Changing it to a json file makes it easier to automatically retrieve and read but makes it even more difficult. As such, the proposal is to move it to the wiki.

**Comment by alamers** [comment]
See [Schemes](https://github.com/adewg/ICAR/wiki/Schemes) for the updated wiki page. I will add a pull request to delete the location.md

**Comment by alamers** [comment]
@erwinspeybroeck : wrt the feed type and feed property enum schemes, am I correct in stating the following:
* the scheme's are "org.fao" and "org.icar"? Do we need further specialization to point to the exact list that we are referring to?
* apparently they both define a numerical id and a technical name for each enum value: do we prefer the technical name?

**Comment by erwinspeybroeck** [comment]
@alamers : the definition of the schemes are provided underneath the mentioned scheme. For the list of the fao a link is included, for the icar list there is nothing to refer to, the list is created and maintained in this wiki (for the moment)

Probably we need to use the technical name as the identifier within the scheme I guess for readibility.

**Comment by alamers** [comment]
I meant: for the FAO enumeration, isn't 'org.fao' too broad? I guess FAO defines other enumerations that we may want to adopt later. As such, the scheme name 'org.fao.feedmaterialsforruminantspecies' would be more precise (but a bit long...)

Also, I'd prefer the technical name as well so let's stick with that and forget about the id's. :)

**Comment by erwinspeybroeck** [comment]
Oh, I understand. In the context of course it is clear, but then I would propose org.fao.ruminants.feedtypes and org.icar.ruminants.feedproperties
If this fits with other schemes like e.g. org.icar.ruminants.breeds I don't know, but we keep everything consistent. Maybe org.icar.breeds would be better since ICAR only takes ruminants into account. Then we would use org.icar.feedproperties.
