### ISSUE TITLE
Missing departureReasonType 

### ISSUE THREAD

**Issue by dirbSEGES** [adewg/ICAR#190]
Hi, 

we need this extra departureReasonTypes: 

Unknown
Metabolic / digestive disorders (maybe nutrition?) 
Other diseases
Diarrhea
Pneumonia
Elevated cell count (bad translation)
Milking time
Accident / Injury
Remediation of specific diseases (bad translation)
Missing milk release(bad translation)

**Comment by cookeac** [comment]
We think most of these are covered by the existing list (some items more general). Is the additional detail required in all cases?

**Comment by dirbSEGES** [comment]
Its most when we recieve data from a client, we can not map the ADE standard to our list. But we have decided to accept this solution.
