### ISSUE TITLE
Add icarDepartureReasonType on icarMovementDeathEventResource

### ISSUE THREAD

**Issue by dirbSEGES** [adewg/ICAR#193]
Hi, 

In case of a death evetn we need to add a reason. So DeathReasonType is needed, it should a be aligned with the departureReasonType. 

Another solution could be that DepartureKindType was extented with 2 ekstra selections Death(deceased) and Culled?

**Comment by ahokkonen** [comment]
We do have field and enumeration for death reason: https://github.com/adewg/ICAR/blob/ADE-1/enums/icarDeathReasonType.json

**Comment by dirbSEGES** [comment]
in our system we do not distinguish between departureReason and deathReason. So if we need to do a correct mapping to our system i need the same reasons i both of them

**Comment by cookeac** [comment]
Resolved as part of #224
