### ISSUE TITLE
Feed Storage (e.g. Silo) in ICAR?

### ISSUE THREAD

**Issue by ghost** [adewg/ICAR#194]
When having a connection between herd management systems, exchanging the feed information (as covered in #93) might not be sufficient. However, is this sort of information covered in ICAR? I believe this is more "process related information", however, it might still be important for the users to exchange that kind of data.

What I'd like to have is a new resource (e.g. feed storage to be generic) that would contain the following info:
* name (string)
* type (string or enum)
* contained feed (reference to feed id)
* capacity (number, connected to unit below)
* quantity unit (enum)
* contained feed amount (number, connected to unit above)

Any opinions on this?

**Comment by ghost** [comment]
I created a first example. Here, the feedStorageResource "inherits" all information from the deviceResource. Would be happy to get feedback.

**Comment by cookeac** [comment]
Resolved by #198
