### ISSUE TITLE
Transponders, Animal Numbers and the ManagementTag on the AnimalResource

### ISSUE THREAD

**Issue by ghost** [adewg/ICAR#195]
There is a "managementTag" on the animal. The description says "The identifier used by the farmer in day to day operations."

This sounds very generic to me. Is this intended to be the transponder of a cow? Or the animal number? Or what else? Maybe we could improve the description to make that more clear.

As a side note: some systems use animal numbers to identify an animal, but these are not "real" identifiers that you might want to add to the "alternativeIdentifieres", as the number might be reused for a different animal if the first animal dies. Same goes for the transponder, I think. Are these inteded to be added to the alternativeIdentifiers, but your results may vary depending on when you query for an animal with a specific identifier?

**Comment by ghost** [comment]
I made a proposal for description changes, please review if you are OK with those.

**Comment by cookeac** [comment]
Resolved by #200
