### ISSUE TITLE
Feed and AnimalSet 

### ISSUE THREAD

**Issue by dirbSEGES** [adewg/ICAR#202]
Hi, 

I´m looking at the feedressources, and can´t find how an amount of consumed feed can be link to a animalSet? In case there is a ration of  ex. TMR fed out for a set of animals. 

I was looking at the FeedIntake and DailyFeedReport, or maybe I´m looking at the wrong resssources? 

Do you had any discussions about this?

**Comment by erwinspeybroeck** [comment]
Hi,
we have been talking about that.

In the feed report we chose to provide the possibility to have an array of animals. We did this since animalSets will change over time.

Regarding the feed intake event we wanted to keep this an event on animal level.

If you have a proposal to improve this please feel free do to so. We looked as this set of feefing API's as a starting point.

**Comment by dirbSEGES** [comment]
Hi, 

Then I propose to add AnimalSet to the DailyFeedReport. My argument is that I believe that animalSet also can be a static definition. (physically defined area - Enclosure or Feeding?)  In the ideal world this sets is always kept up to date with the correct animal-indentifiers, but unfortunately is our experience that it is not so.

**Comment by ghost** [comment]
I'd propose a slightly different way. IMHO, animal sets can reference a physical area (or something completely different like a list of my favorite cows), but nevertheless, the content of the set can change over time (e.g. lovely Berta stepped on my foot so I don't like her anymore).

A feed report that is retrieved from a system, however, is something static. The feed that the cows have eaten will not change anymore and the animals that are contained in the report will also not change. Until time travelling proves me wrong :)

Hence, I'd argue against referencing animal sets in the feed report, as this would reference non-static data in a static context. However, I can see that it might be convenient to retrieve a feed report for a currently defined animal set.

After all, I think the definition of the API to retrieve feed reports is not yet complete (see #93) as one can currently not specify for which animals one wants the report for and for which time frame. There, it should be possible to define the animals you want to look at. Then, if you want to look at the feed report for an animal set you can just read the animal set first and use the animal identifiers to retrieve the report you want to have. If you need historic information about a specific animal set, however, you have to somehow get the info which animals where in the group at your targeted point in time. The ICAR api does not provide that information (and maybe some systems might not even track the historic develoment of animal sets) and, hence, cannot provide that info automatically.

If you need to know which animal sets the feed report that you queried belongs to, I think you need to track that info in another place (i.e. not ICAR api) where you relate the feed report to just a name of an animal set at a point in time.

BTW: the daily feed report is already in the develop branch, but I couldn't find an enpoint to retrieve it. So I think this is also not complete, yet. But this is a discussion for #93.

**Comment by ghost** [comment]
Update: in #93 we propose that the daily feed report is removed for now in favor of just using the feed report while specifiying the start and end of the day you want to have info about. Also, we suggested that you can reference a single animal for which you want to have the report or an animal set. However, as the set can change over time, subsequent requests for the same animal set id could report different results depending on whether the animals in the set have changed or not.

Now, if you want to get a feed report for a specific set of animals, you could just create a new animal set with the animals you want to have in there and then you can query the feed report for those. You can then even remove the animal set again, if you don't need it anymore.

**Comment by cookeac** [comment]
@dirbSEGES is Thomas' response above sufficient? If so, we can make this a Documentation issue.

**Comment by cookeac** [comment]
Addressed with PR #244 and Wiki page https://github.com/adewg/ICAR/wiki/Feed-Reporting
