### ISSUE TITLE
Code generation from API specification.

### ISSUE THREAD

**Issue by MarkLaarakkers** [adewg/ICAR#205]
Hi,

I'm having troubles generating code based on the exampleUrlScheme.json. If I view this schema in swagger and can see for example, that a treatment has a medicine/batches/dose. 

Using swagger (https://editor.swagger.io/?url=https://raw.githubusercontent.com/adewg/ICAR/ADE-1/url-schemes/exampleUrlScheme.json) to generate a client or server (For example on the top of the swagger page "Generate Client" -> "csharp"). Will yield an zip file with generated code, the models however are only "empty" collections. There are no references to fore example the medicine/batches/dose.

using autoreset to generate code also does not seem to work and cannot generate usable code and seems to indicate an errors in de models. e.g.
`WARNING (Modeler/MissingType): The schema 'icarLocationCollection' has no type or format information whatsoever.`

Is this something needs to be changed in the specification? Or could you recommend a tool which can correctly generate code based on this specification?

**Comment by ahokkonen** [comment]
Hi @MarkLaarakkers,

Swagger online tools (CodeGen) are quite non-functional when using them directly from url reference.
Best way to generate code out of OpenAPI specs is to download sources and execute code generation locally.

I would prefer **not** to use GenTools provided by Swagger, but to use [openapi-generator](https://github.com/OpenAPITools/openapi-generator) instead.

I was able to do code generation without any problems by taking ADE sources locally, installing openapi-generator via NPM and running generation command like (check tool specs for more configuration):

`openapi-geneator generate -g csharp -i url-schemes/exampleUrlScheme.json -o output`

**Comment by MarkLaarakkers** [comment]
Hi @ahokkonen 

Thank you for the help. Using the openapi-generator the models where generated without problems.
