### ISSUE TITLE
icarFeedQuantityType mass unit codes

### ISSUE THREAD

**Issue by ahokkonen** [adewg/ICAR#211]
@erwinspeybroeck @thomasd-gea 

just noticed that we have definition for units in "[icarFeedQuantityType](https://github.com/adewg/ICAR/blob/Develop/types/icarFeedQuantityType.json)" which potentially could be combined into the mass unit types that we already have in standard [uncefactMassUnitsType](https://github.com/adewg/ICAR/blob/Develop/enums/uncefactMassUnitsType.json)

Or maybe better solution to have separate unit type for feeds?

**Comment by cookeac** [comment]
Will be fixed by #212
