### ISSUE TITLE
New values for production purposes - Breeding, SucklerCow

### ISSUE THREAD

**Issue by ahokkonen** [adewg/ICAR#215]
We would like to have additional values for production purposes - **Breeding** and **SucklerCow**.
Is this something also used outside Nordic? @cookeac @alamers @erwinspeybroeck  

```json
{
	"type": "string",
	"enum": [
		"Meat",
		"Milk",
		"Wool",
		"Breeding",
		"SucklerCow"
	]
}
```

**Comment by erwinspeybroeck** [comment]
It is not used in the Netherlands or Flanders.
Only remark that I have is that breeding en sucklercow can refer to milk or meat - that might complicate it a bit.
But not a real objection to add it.

**Comment by ahokkonen** [comment]
Yes, agree, so technically it could be "multi-purpose" which we do not support in ADE.
...and at the end they all are meat :)

**Comment by cookeac** [comment]
Yes, its not a super-helpful enumeration. It was intended to look at the primary "product" that is being produced, and hence the focus of performance breeding objectives.

Suckler cow enterprises are typically for meat but can be for milk. In contrast, I think breeding in the sense of a primary product being stud animals for sale is valid.

If we were doing this now I would suggest an array of these enumerated values.

**Comment by alamers** [comment]
Also: the naming `SucklerCow` is quite cow-specific, do we want to generalise that?
