### ISSUE TITLE
icarDailyFeedReportCollection refers to non-existing icarDailyFeedReportResource

### ISSUE THREAD

**Issue by ahokkonen** [adewg/ICAR#216]
In "collection" folder icarDailyFeedReportCollection refers to non-existing icarDailyFeedReportResource
("$ref": "../resources/icarDailyFeedReportResource.json")

As linter is only checking resources defined in url scheme this issue has "leaked through" :)

We might want to improve spectral checks for all *.json in the project.

**Comment by erwinspeybroeck** [comment]
sorry, my fault. We decided not to use icarDailyFeedReportResource and I removed it without thinking about the icarDailyFeedReportCollection - it can also be removed ...

Of course extra check would help to avoid this.

**Comment by ahokkonen** [comment]
I can improve some linter action in my next PR

**Comment by erwinspeybroeck** [comment]
should i wait to remove the collection, so we can see your change works?

**Comment by ahokkonen** [comment]
If you want - I can remove it in my PR among other changes (not sure if I'll be able to produce one before tomorrow).
If you don't have some code change already coming from your branch..

**Comment by erwinspeybroeck** [comment]
Ok, no problem - you can remove it.

**Comment by erwinspeybroeck** [comment]
the unused resource has been removed
