### ISSUE TITLE
Milking-Statistics

### ISSUE THREAD

**Issue by AndreasSchultzGEA** [adewg/ICAR#218]
We are thinking of new resource containing a set of milking-statistic values. 

In difference to the proposal #184 , this resource should contain information about
* a single aninmal
* of a dedicated day

Proposed attributes are at the moment: 
* Average milking-yield last 24h
* Average milking-yield last 7 days
* etc.

**Comment by cookeac** [comment]
Agreed this seems to be daily average milking statistics - @AndreasSchultzGEA to submit a PR

**Comment by cookeac** [comment]
DailyMilkingAveragesResource ?

**Comment by cookeac** [comment]
I believe this is closed by #225
