### ISSUE TITLE
TreamentProgramRessource?

### ISSUE THREAD

**Issue by dirbSEGES** [adewg/ICAR#219]
Hi, 
When we are looking at [TreatmentProgramEventResource](https://github.com/adewg/ICAR/blob/ADE-1/resources/icarTreatmentProgramEventResource.json). 

As I understand, is the ressources to create a treament on animal, based on a program.  I can´t find a ressource to get the available TreamentPrograms on a location?  How to do this?

**Comment by cookeac** [comment]
A Treatment Program is not a pre-defined entity (for instance "available treatment programs") but instead is a way of defining a set of treatment events for an animal and relating them to the diagnoses that the treatments are addressing. This is used where farmers or vets specify a number of treatments and total dose (for instance), rather than recording the discrete treatment events.

In the example URL scheme, `GET /locations/{location-scheme}/{location-id}/treatment-programs` may be used to get treatment programs for a location.

**Comment by erwinspeybroeck** [comment]
We are using something we called TreatmentProgramTemplates in which somebody can define standard treatment programs. Somebody can then use such a template to define a program. Is it something like that you want to define?

**Comment by dirbSEGES** [comment]
Yes, but not a template, it´ s more predefined treamentsprogram for the common diagnoses at the location. In our system the vets will describe a treamentprogram or plan for the most common diagnoses at the location. When the farmer start a treatment he select the program/plan and recieve the predefined medications and dosis and the number of retreaments. 

Then he base his treamentsregistrations on the program/plan.

**Comment by erwinspeybroeck** [comment]
yes, but that is what I mean by a template - from this template a plan is derived. when deriving you can take the information from the template (like which treatments, medicines, doses, ...) and use it in a treatment program for an animal.
In the standard we have not defined anything for a template (yet).

**Comment by dirbSEGES** [comment]
Ok, I understand you.  

TreatmentProgramTemplates could include "Treament"(icarTreatmentEventResource) and "Diagnosis"(icarDiagnosisType). "Courses" could also be used if it could be expanded with "numberoftreaments", "days(orPeriod)betweentreaments"

**Comment by cookeac** [comment]
I agree, it would make sense to add to **icarMedicineCourseSummary**:
* numberOfTreatments - integer
* treatmentInterval - integer (in days)

**Comment by cookeac** [comment]
Discussed whether treatmentInterval should support hours or part-weeks. We should be explicit about the units used (Hours?).

**Comment by cookeac** [comment]
I have a PR to submit that should resolve this.
