### ISSUE TITLE
IcarMilkingVisitEventResource, extend with exemptFromRecording

### ISSUE THREAD

**Issue by AndreasSchultzGEA** [adewg/ICAR#220]
IcarMilkingVisitEventResource does contain the existing attribute 'milkingComplete', which provides the information if there have been mostly technical reasons why the MilkingVisitshould be regarded to be imcomplete.

We suggest to extend IcarMilkingVisitEventResource with an additional attribute 'exemptFromRecording', 
which indicates, that the milking-result is not reliable for other reasons (separations, e.g.).
@ahokkonen: please provide the lookup-list which is used in Nordics.

**Comment by ahokkonen** [comment]
In NCDX data exchange we use such field "ExemptFromRecording" for indicating if sample result should be ignored from recording. In Finnish database field is called "TestMilkingException".

We use it only for sampled milkings, but in ADE we can extend the use also for all milking visit if required.
We use predefined parameters:

**Finland**
- Normal test milking (default if not specified)
- Sick, no test milking
- Sick, test milking done
- Milked separately, sample sent
- Milked separately, no sample
- Sample spoiled

**Norway**
- Normal test milking (default if not specified)
- Sick, no test milking

**Comment by tpekeler** [comment]
We checked with our local experts for Germany.
The Entity 880022 (milking-automated) in ADIS has different Items for both purposes:
800701/milked corresponds to milkingComplete (0=false, 1=true)
800703/event-of-milking refers to some reason for exception (3  char codes)

We decide on our own whether to record the milking or not.
Therefore a name like milkingEvent is better suited than exemptFromRecording

**Comment by AndreasSchultzGEA** [comment]
I agree to Thomas, that 'milkingEvent' or even '**eventOfMilking**' is a better naming than 'exemptFromRecording'.
The attribute should be null in the case of no information.
In other cases, possible values could be:
* sickness,
* separated (in concerns of at least one separated teat)
* milked separately

Do we need a differentiation between normal MilkVisits and MVs with sampling?

**Comment by AndreasSchultzGEA** [comment]
After discussing, instead of milkingEvent/ eventOfMilking we would like to suggest the additional attribute named '**milkingRemarks**', as it fits better the usecases described by Anton as well as our own.

The milkingRemarks could either be a 

- list of possible enum-values like ['animal sick', 'separated', 'milked separately', 'sampling failed', ...], or
- a new resource which contains boolean flags for each of the necessary information, e.g.: 
  { "sickAnimal": true/false, "separated": true/false, "separatelyMilked: true/false, "failedSampling": true/false, ...}

**Comment by cookeac** [comment]
Add "milkingIncomplete" to the remark array as well (and keep the existing numeric flag as well for backward compatibility).

We liked the idea of an array. Ideally an array of enumerations (because of flexibility and ability to have combinations) but noting this could end up with duplicates, in which case the object with booleans would be a better idea.

Thomas and Andreas will make a pull request proposal.

**Comment by AndreasSchultzGEA** [comment]
[PR](https://github.com/adewg/ICAR/pull/222) is provided

**Comment by cookeac** [comment]
Resolved by #222
