### ISSUE TITLE
Add "PregnantMultipleFoetus" in the icarAnimalReproductionStatusType

### ISSUE THREAD

**Issue by dirbSEGES** [adewg/ICAR#223]
Hi,
We need "PregnantMultipleFoetus" in the enumeration of AnimalReproductionStatus.

**Comment by cookeac** [comment]
Let's discuss this with the group -- we already have the Pregnancy Check event that covers this, but there may be merit in also making it a status value.

**Comment by cookeac** [comment]
We agreed we could add this.
