### ISSUE TITLE
Extension to IcarMovementDeathEventResource

### ISSUE THREAD

**Issue by AndreasSchultzGEA** [adewg/ICAR#224]
At least in Germany, the ADIS-format is very common at official institutions.
In the case of DeathEvents, the mapping from a FMS to ICAR to ADIS and vice versa is not unique, as the MovementDeathEvent has only one attribute 'deathReason' with values ( "Missing", "Parturition", "Disease", "Accident", "Consumption", "Culled", "Other", "Unknown").

But ADIS requires 2 attributes within the death-message:
ADIS-Codes   882083:
- 820064 Todesart/DeathKind (with values 1= verendet/ perish, 2= Hausschlachtung/ slaughter, 3= Tötung/ culled, 10= Diebstahl/ theft, 11= nicht auffindbar/ lost, 12= nicht identifizierbar/unknown , 13= nicht nachvollziehbar/ other reason)
-  800041 Abgangsgrund/ DeathReason (with values: 1 - Verkauf zur Zucht/ sale, 2 - Alter/ age, 3 - geringe Leistung/ productivity, 4 - Unfruchtbarkeit/Fertility , 5 - sonstige Krankheiten/ other diseases, 6 - Euterkrankheiten/Mastitis, 7 - Melkbarkeit/MilkingAbility, 8 - Klauen und Gliedmaßen/LegOrClaw, 9   sonstige Gründe/other reasons, 10 - Stoffwechselkrankheiten/Nutrition, 11 - Abgang des Betriebes/end of farm, 12 - Problematisches oder aggressives   Tierverhalten in der Herde/ behaviour in herd, 13 - Problematisches Tierverhalten beim Melken/ behaviour at milking)

As it is essential for Germany, that the ICAR to ADIS and the ADIS to ICAR mapping could be executed without huge loss of information, we suggest the following:
1. introduction of a new attribute '**deathKind**' within MovementDeathEvent which contains the 'Coded kind of death including slaughter, culled, perish'.
2. furthermore, the _extension_ of the existing '**deathReason**'-attribute of MovementDeathEvent with the following values:
- Age,
- Mastitis,
- Production,
- LegOrClaw,
- MilkingAbility,
- Nutrition,
- Fertility

**Comment by cookeac** [comment]
We have already added (in Develop branch) a DeathMethod (rather than DeathKind), which has some of these fields. 
The list looks useful to me, so I will modify enum/icarDeathMethodType.json and enum/icarDeathReasonType.json as advised.

**Comment by AndreasSchultzGEA** [comment]
Then, the delta between 'DeathKind' and 'DeathMethod ' is just a missing 'slaughter'.
And the extension to 'deathReason' is described as above

**Comment by AndreasSchultzGEA** [comment]
What about 'perish' as a new death reason? May this also be included within this PR?
