### ISSUE TITLE
move the $ref links to relative urls

### ISSUE THREAD

**Issue by alamers** [adewg/ICAR#23]
Currently the $ref's are absolute URL's pointing to the adewg's master branch. This makes it hard to test and verify in other repositories.

We should check if we can simply make them relative to the (example) url scheme.

**Comment by cookeac** [comment]
Relative URLs can work well for JSON Schema (at least for me using VS Code and the ES Lint plug-in etc), but this is not necessarily the case for all parsers and validators. Some developers may need to be explicit in their parameters to their parser/validator to a) have it load referenced schemas and b) provide the paths in which the parser/validator should look for those referenced schemas.
I will ask other methods of our team here about use with OpenAPI/Swagger.

**Comment by cookeac** [comment]
See also https://swagger.io/docs/specification/using-ref/

**Comment by cookeac** [comment]
Summarising the out-of-band email conversation here between Arjan, Erwin, and I:

a. The $refs have now all been made relative.
b. Swagger Editor has some problems with these.

You can open the url scheme if you provide a URL parameter:
Open the editor with: http://editor.swagger.io/?url=https://raw.githubusercontent.com/adewg/ICAR/master/Release%20Candidate%20Messages/exampleUrlScheme.json
This will allow the editor to resolve all relative url’s based on the given URL parameter. 

Arjan has added this URL to the Wiki pages as well:
https://github.com/adewg/ICAR/wiki/Implementing-a-client-application
https://github.com/adewg/ICAR/wiki/Implementing-a-service

Closing this issue as complete (reopen if you disagee).
