### ISSUE TITLE
Alternative Type for Coat Color

### ISSUE THREAD

**Issue by ghost** [adewg/ICAR#240]
As mentioned in our meeting on 12.08.2021:

The coatColor property of the icarAnimalCoreResource.json states:
`Colour of the animal's coat, using the conventions for that breed.`

That is not very helpful as it seems to imply that the primary breed scheme/identifier should have an influence on this. As discussed, there would be two ways on how we can improve this:

1. change the coatColor to contain an enum value (have to make a list of all possible coat colors and each receiving party has to maintain a mapping from possible coat colors to its own list of allowed values)
2. use scheme/identifier instead to allow for different enumerations per country/organization/... (but we could still provide a default scheme, if we want to)

Any opinions which way to go?

We should also decide if this should be solved in a 1.x release, because then we have to add an additional field for the new coat color to be backwards-compatible and might have to rename it for a 2.x version.

**Comment by erwinspeybroeck** [comment]
Color codes in Netherlands:
[ BLACK, BLACK_AND_WHITE, BLACK_WHITE, BLACK_SPOTTED_PIED, BLUE_AND_WHITE, BROWN, FAWN_PIED, GRAY, RED, RED_AND_WHITE, RED_WHITE, RED_SPOTTED_PIED, TRICOLOR, WHITE, WHITEBACKED_RED, WHITEBACKED_BLACK, WHITEHEADED_RED, WHITEHEADED_BLACK ]

Color codes in Belgium:
[ BLACK, BLACK_AND_WHITE, BLUE_AND_WHITE, GRAY, RED, RED_AND_WHITE, WHITE, DARK_BROWN, LIGHT_BROWN, MICE_BROWN, WHITE_AND_BLACK, WHITE_AND_BLUE, WHITE_AND_RED ]

In Belgium color codes are really only I&R related, in the Netherlands the breeding organisation had more to say ;-)

**Comment by ghost** [comment]
From LKV in NRW/Germany (ADIS Dictionary):

http://ian.lkv-nrw.de/index.php?id=292&vURL=AGRO2018%2Fc810026.html&cHash=82f66ea378

[ Other, Black, Brown, Red, Gray (as the color), White, Saddled (? "gesattelt"), ("Schimmel" = completely white), Blonde, False Color ("Fehlfarbe")]

**Comment by ghost** [comment]
Maybe one thing in favor of schema/identifier: I guess sheep, horses, pigs, cows etc. might have highly different coat color values. Therefore, the question is for me whether a large enum of all values makes really sense because you then need to map specific pig or horse colors even if you only want to exchange cow data...

**Comment by AndreasSchultzGEA** [comment]
PR at https://github.com/adewg/ICAR/pull/252
