### ISSUE TITLE
Adding a reason for DoNotBreed event

### ISSUE THREAD

**Issue by ahokkonen** [adewg/ICAR#250]
We've received a proposal/request on extending [DoNotBreed](https://github.com/adewg/ICAR/blob/ADE-1/resources/icarReproDoNotBreedEventResource.json) resource with the "reason" enum field (potentially party based on departure reasons)

Does anyone feel this could be a valuable addition to the standard?

**Comment by erwinspeybroeck** [comment]
We use the remark for this. If we go for the solution from https://github.com/adewg/ICAR/issues/233 then this will automatically part of it

**Comment by cookeac** [comment]
We agree with adding a Remark (#233) unless there is a strong common list of values we should consider.

**Comment by cookeac** [comment]
Unlinked from #256. We've decided that there could also be value in a *reason* attribute which was an enumeration, in addition to a user-editable remark string.
