### ISSUE TITLE
Insemination: additional AICode, Station and Technican for Sire

### ISSUE THREAD

**Issue by AndreasSchultzGEA** [adewg/ICAR#261]
At least one German official organisation (for reproduction, e.g. LKV Brandenburg) demands the additional Artificial-Identification-Code of a sire, the insemination-station the straw is taken from and the technican who executed the insemination to be included into the insemination-events.
All three attributes should be of type string. The AICode may e.g. be a composition of 'official herdbook no' and a station-specific part.

**Comment by erwinspeybroeck** [comment]
SireIdentifiers is an array - there you should include  the additional Artificial-Identification-Code of a sire. 
The insemination station is part of the "straw" sub resource --> CollectionCentre.
The technician is supposed to be mentioned in the responsible field

**Comment by AndreasSchultzGEA** [comment]
Thanks for the hints, Erwin
