### ISSUE TITLE
Add isDeleted to meta

### ISSUE THREAD

**Issue by gra-moore** [adewg/ICAR#265]
For the streaming protocol to work it is necessary for resources to indicate if they have been deleted. 

Proposal is to add a isDeleted boolean to the meta structure.

This is backwards compatible and makes sense alongside the other meta properties. 

The value is optional and defaults to false.

**Comment by gra-moore** [comment]
It would look something like this:

`{
  "description": "Generic meta data on this resource",

  "type": "object",

  "required": [
    "source",
    "modified"
  ],

  "properties": {
    "source": {
      "type": "string",
      "description": "Source where data is retrieved from. URI  or reverse DNS that identifies the source system."
    },
    "sourceId": {
      "type": "string",
      "description": "Unique Id (ideally UUID) for the resource in the original source system. Treat source and sourceId as an icarIdentifierType."
    },
    "isDeleted": {
      "type": "boolean",
    },
    "modified": {
      "$ref": "../types/icarDateTimeType.json"
    },
    "created": {
      "$ref": "../types/icarDateTimeType.json",
      "nullable": true
    },
    "creator": {
      "type": "string",
      "description": "Person or organisation who created the object"
    },
    "validFrom": {
      "$ref": "../types/icarDateTimeType.json",
      "nullable": true
    },
    "validTo": {
      "$ref": "../types/icarDateTimeType.json",
      "nullable": true
    }
  }
}`

**Comment by cookeac** [comment]
Resolved by #280
