### ISSUE TITLE
Add semantic type to resource

### ISSUE THREAD

**Issue by gra-moore** [adewg/ICAR#266]
The streaming API but many other contexts it is valuable for a resource json fragment to clearly indicate what kind of thing it is.

Proposal:

add a new property to resource called: icarType whose value is a URI. 
define a list of URIs for all existing ICAR types.

The property is optional. 
For the purposes of the protocol this property would need to be present.

This change is backwards compatible.

**Comment by gra-moore** [comment]
proposed icarResourceType

**Comment by gra-moore** [comment]
proposed resourceType

**Comment by cookeac** [comment]
Resolved by #279
