### ISSUE TITLE
Add location or context to resource

### ISSUE THREAD

**Issue by gra-moore** [adewg/ICAR#267]
For the streaming API it is necessary to provide context regarding which farm or account the data is related to. 

Options:

1. Add Location as a property of resource. This is backwards compatible. Any resource definitions on subtypes would be moved up to resource. 

2. Add a 'context' property to meta that allows for this to be conveyed in an application independent way.

In either case the API spec would need to declare which properties are required and how they should be interpreted, 

Thoughts: the use of context is a light binding and doesnt change the model at all.

**Comment by gra-moore** [comment]
Proposal: (1)

**Comment by cookeac** [comment]
This is in progress in current pull requests.

**Comment by cookeac** [comment]
Resolved by #281
