### ISSUE TITLE
Add event resources for sets (groups) of animals

### ISSUE THREAD

**Issue by cookeac** [adewg/ICAR#273]
A question passed on from members of the ICAR ADE group: should it be possible to record events for sets of animals (groups)? What would be the semantics of this?

I am unsure of the demand for this. Some places where this could be useful:
- Have have applied a standard animal health treatment (for instance a drench or oral wormer) to a group of animals.
- I moved a group of animals to a different sublocation (paddock/field) at a farm location (an event we don't have)

Depending on the semantics, this could just be a shorthand for batch applying an event with the same observed values to many individual animals. Or it might mean that the group of animals was identified prior, and I have applied the event to that group without checking that all the individuals were present -- this would be subtly different.

I would value thoughts or feedback that I could provide as feedback to the ADE group.

**Comment by cookeac** [comment]
After discussion with a few organisations, it seems that it would be useful to be able to record data for a **set of animals** with two variations. This is data that is difficult or not meaningful to record precisely on individuals because of how the operations or observations are carried out:
Specific examples include:
* Feeding event where a ration of feed is fed to a group of animals in an open field or yard, and individual rations cannot be confirmed.
* Grazing events where a mob or group of animals is moved onto a new forage or forage allocation without individual animals being scanned.
* Mob sample weights where a sample of animals is weighed to be representative of the group, without necessarily identifying the individuals being weighed. For instance, in a sheep mob of 1000 animals, a sample weight may be done for 50 animals to save time.
* A group of animals are drenched, put through a foot bath, or otherwise treated together in bulk without scanning individual IDs.

A common factor for these events is that they are unlikely to be used for genetic improvement because individual animals are not identified or certain, but they can be used for farm management, feed analysis, and herd health records.

Potential solution:
* Define an equivalent to icarEventCoreResource that has an animal set reference rather than an animal identifier
* This event would also specify the number of animals believed to have been observed/treated (because the event occurs at a point in time, while animal set membership may change over time).
* Derive special purpose events for these feed, weight, grazing, and treatment events that recognise they are being used for a set of animals.

I mentioned two variations to this case:
1. An animal set is available which defines the known membership of the set (it is just that the exact animals observed are not known for the event)
2. The exact animals are not known at all (for instance, extensive grazing of sheep where individual IDs are not recorded) but the "composition" of the animal set is known -- for instance, there are 1000 adult female sheep. It would be possible to create a "Composition" object that could be embedded into the animal set events.

**Comment by cookeac** [comment]
After discussion on 7 April 2022, we noted:
* Only a subset of events would make sense to record on a mob/group/set basis. These would include feed, treatment, weight samples, etc as above.
* Set data is unlikely to be useful for genetic/breeding decisions but could be useful for other farm management, biosecurity, and inventory purposes (so within the scope of animal recording).
* Set membership is not guaranteed to be managed over time by all systems, so if an icarAnimalSet was used, it would need to be "informational" as membership may have changed since the event was recorded.
* Some systems might interpret a set event that did have a list of animal identifiers by creating individual animal events (for instance, a drench applied to an animal set might apply that drench to all the individuals). This would be fair, but implementation dependent.
* The ability to describe the set by its overall composition (number of animals by species, sex, age, BREED, reproductive status) is probably more portable and usable than the list of members for the reason above.

We also decided that:
- It would be elegant to change `icarEventCoreResource` to remove the animal identifier, then create `icarAnimalEventCoreResource` to add the animal identifier and incorporate this with $ref wherever `icarEventCoreResource` is currently incorporated. This would be a non-breaking change for implementers.
- Then an `icarSetEventCoreResource` could be created to add composition, number, and animal set reference.
- Common attributes (for instance, treatment details), could be handled across individual animal and set events by generalising these to a type that was incorporated into both events. Other events like sample weights would be quite different from their individual animal counterpart.

**Comment by cookeac** [comment]
Here is a conceptual set of changes that would support the discussion above. Examples are a Weight event (quite different properties for group sample vs individual) and a Treatment event (essentially the same properties for both).
Suggested changes and new entities are shown in pink.
![class diagram](https://github.com/adewg/ICAR/blob/Develop/wiki-images/ICAR%20Animal%20Events1.png?raw=true)

**Comment by cookeac** [comment]
At our meeting on 2022-08-25 we agreed that this seems good as long as code generation still works well (i.e. moving animal reference doesn't break anything).
@AndreasSchultzGEA and @AlexeyHardCode will have a look with their respective language code generation to assess.

**Comment by cookeac** [comment]
Noted at the meeting 08 Sep 2022 that Andreas has tested and it is ok.

**Comment by AlexeyHardCode** [comment]
Verified code generation with csharp-netcore.  Events hierarchy looks same way as it should. From my side all good.

**Comment by cookeac** [comment]
Great, thanks
