### ISSUE TITLE
DELETE-calls for batches

### ISSUE THREAD

**Issue by AndreasSchultzGEA** [adewg/ICAR#277]
The ReST-standard seem not to define how to handle bodies in DELETE-calls. Therefore, the usage of DELETE-batches is not possible without problems.

**Comment by gra-moore** [comment]
RFC2616 https://datatracker.ietf.org/doc/html/rfc2616/#section-9.7 is seems silent on what it means to send a body on a delete request. So it could be OK, but I agree it feels very wrong and I haven't seen this approach being used. 

An idea in the direction of

- POST a batch txn resource to /txns where the body is a structure indicating the resources to delete.
 
Would feel more natural to me.

**Comment by cookeac** [comment]
Options we discussed:
- A batch as a resource that could have an ID and URL and be DELETED (this is most consistent with our current use of batches)
- Defining an Animal Set and then having a mechanism to DELETE animals in that set
- Having Delete_Notifications (like events or messages), identifying resources to delete
- Programatically deleting resources one by one (probably the most pragmatic)
- Using a streaming API with delete notifications
