### ISSUE TITLE
"endDate" is not nullable IcarLacationRessource

### ISSUE THREAD

**Issue by dirbSEGES** [adewg/ICAR#282]
Hi, 

I´m not sure if it´s at issue here, but need the "endDate" to be nullable. In case of open lactation. 

But maybe it is a issue concerning the code generator?

**Comment by cookeac** [comment]
It is not a required field. Are you saying that null should be a provided value rather than just not supplying the value? This does sound like code generation or language libraries may be ignoring required status.
