### ISSUE TITLE
Consider mandating RFC3339 instead of ISO 8601

### ISSUE THREAD

**Issue by gra-moore** [adewg/ICAR#286]
https://ijmacd.github.io/rfc3339-iso8601/ Might get us closer to the uniformity we expressed we wanted to see in date time representations.

**Comment by cookeac** [comment]
We recommend the group consider this, but **also** we should modify the example URL Schemes to show the format that is expected.

**Comment by alamers** [comment]
We should also update https://github.com/adewg/ICAR/wiki/Design-Principles#dealing-with-time then.
