### ISSUE TITLE
Severity code for animal health diagnosis

### ISSUE THREAD

**Issue by cookeac** [adewg/ICAR#297]
From discussions with the ICAR Functional Traits working group, it would seem valuable to add a `severity` property to the [icarDiagnosisType](https://github.com/adewg/ICAR/blob/ADE-1/types/icarDiagnosisType.json).

Email from Christa (in the context of a discussion about diagnosis coding, which is already catered for):

> I think that  it would be helpful if also some ‘optional’ information could be transmitted also
> Animal
> Farm
> Date
> Heath code (if not the ICAR Health code is used – it is needed that the information about the key and the technical term is available)
> Source of information / type (veterinarian, farmer, lab (if lab information is also included), hoof trimmer,…) (if available)
> Location (optional - if available ) – if have not standardized it for claw lesions – but it is partly available) – the question is also if this interface should accommodate also bacteriological findings (then location would be also needed)
> **Severity (optional – if available) – we have not standardized severity for the claw lesions – it was the assumption that we would not manage to standardize it) – but if it is available it should be able to transmit**
> Person of recording (optional if available)

Kathrina then added:
> Dear all,
> just a brief comment on the severity of health events (actually underlining of what Christa had already written): Experience from projects and routine has shown that even with training of those people who are recording the health events, severity recording remains on a high level of heterogeneity. Because there are usually several criteria for lower or higher severity (size, depth, color, temperature, pain) which do not necessarily develop in parallel, data recording and exchange may surely include the severity grade, but we need to be careful with what we collect. Reliable interpretation may not be possible.
> Best regards
> Kathrin

This implies that it won't be possible to define a single enumeration (especially as various diseases have different severity coding).
There are two potential methods to support this:
1. `"severity": "string"`
2. `"severity": "icarDiagnosisSeverityIdentifer"` (an identifier type so that severities could identify which scheme was being used).

**Comment by erwinspeybroeck** [comment]
We have an application with which claw health data is collected by hoof trimmers.
The severity codes used there (for Mortellaro, foot rot, sole ulcers, laminitis,  ...) :
- beginning
- acute/active
- chronic
In other diagnosis we use mostly:
- light
- moderate
- severe
-

**Comment by cookeac** [comment]
Until the Functional Traits working group propose a guideline, perhaps implementers could define their own non-standard specification (i.e. separate field outside the schema that is named to avoid collisions).

**Comment by cookeac** [comment]
I did some more research @erwinspeybroeck. It seems in many diseases there is a stage classification which has these values:
* Early
* Acute
* Sub-acute (healing or degenerating past acute)
* Chronic
* Acute-on-chronic (chronic which has been re-exacerbated)
* End-stage (possibly - I've only seen this in one case).

It might be appropriate for a light/moderate/severe/extreme scale to be used for `severity`, and have a separate `stage` that could be used for your application.

**Comment by erwinspeybroeck** [comment]
I agree - it seems logical

**Comment by cookeac** [comment]
At our meeting 2022-08-25 we agreed that it makes sense to separate `severity` and `stage` into two separate fields within `icarDiagnosisEvent`. @cookeac will propose these and send to the Functional Traits Group to ensure no objection.
