### ISSUE TITLE
Separation of Milk

### ISSUE THREAD

**Issue by AndreasSchultzGEA** [adewg/ICAR#318]
How to handle the separation of milk in the case of
* parturition -> colostrum
* treatment,
* etc.

**Comment by cookeac** [comment]
Possibly create an event to reflect that this works like a withdrawal period for a health treatment, but separate it from a health treatment that might require milk to be disposed -- this is milk that would be set aside for colostrum.

We looked at alternatives - using the treatment event and expanding the withdrawal type.
We also considered (but declined) using animal sets (requires active maintenance daily) or animal health status.

**Comment by cookeac** [comment]
Resolved by #320
