### ISSUE TITLE
icarReproParturitionResource.ProgenyDetails missing from ADE 1.2?

### ISSUE THREAD

**Issue by cookeac** [adewg/ICAR#319]
It appears these were merged into **Develop** branch on 2021-09-05 and ADE 1.2 was released on 2021-09-16, so we expected these would be in ADE 1.2. However, they don't appear in the **ADE1** branch?

Raised by @tpekeler and reviewed at the meeting on 8 September 2022. This does seem to be the case.
@cookeac will investigate more. The solution will be to promptly get ADE1.3 released.

**Comment by tpekeler** [comment]
There seems to be more missing in ADE-1 branch. We switched to Development for generating all new sources, but this is confusing to other partners following the guidelines to rely on ADE-1 branch. Maybe there are some errors in the toolchain.

**Comment by cookeac** [comment]
Do we know what else might be missing @tpekeler? 
I can see the PR #245 from Develop into ADE1 on 2021-09-16
https://github.com/adewg/ICAR/commit/b10d8d7ad6a291710e093493573fb6fe8e26469b

The ProgenyDetails were added to icarReproParturitionEvent in a commit on 2021-09-05 BUT this was in a PR from a separate branch which was merged into Develop on 2021-09-24 - AFTER the ADE 1.2 release (see PR #243). 
https://github.com/adewg/ICAR/commit/b3bcb19fb064b6d3ba484988ee37f59f78acb1c2

So the PR with these was created BEFORE ADE 1.2 release, but only merged into Develop AFTER the release.

**Comment by tpekeler** [comment]
Obviously the PogenyDetailsResource is missing too. What else I cannot say for sure. We are developing some automated Tool to compare the iDDEN implementation to the latest ADE release. Maybe we can use this to investigate a little more.

**Comment by cookeac** [comment]
Yes, it seems that the PR that Anton had opened for Progeny Details had not been reviewed by participants at the time we released v1.2. See the minutes immediately after the 1.2 release - https://github.com/adewg/ICAR/wiki/Technical-Minutes-2021-09-23. At the time we thought that v1.3 would be completed quickly, so this was not a problem.

**Comment by cookeac** [comment]
We would like to release v1.3 as soon as possible.

**Comment by AlexeyHardCode** [comment]
Enums are missing as a separate file:
1.	DurationUnit (icarFeedDurationType, icarMilkingMilkWeightType)
2.	MilkWeightUnit (icarMilkingMilkWeightType) 
3.	OperationMethod (icarResourceCollectionReference)
4.	 OperationType (icarResourceCollectionReference)
5.	PlanOrActual (icarMedicineCourseSummaryType) 
6.	ReferenceType(icarResourceCollectionReference)
7.	QuarterId (icarQuarterMilkingType

**Comment by AlexeyHardCode** [comment]
In compare to iDDEN Hub latest version, ADE 1.2 version has following differences: 

Enums are missing as a separate file:
1.	DurationUnit (icarFeedDurationType, icarMilkingMilkWeightType)
2.	MilkWeightUnit (icarMilkingMilkWeightType) 
3.	OperationMethod (icarResourceCollectionReference)
4.	OperationType (icarResourceCollectionReference)
5.	PlanOrActual (icarMedicineCourseSummaryType) 
6.	ReferenceType(icarResourceCollectionReference)
7.	QuarterId (icarQuarterMilkingType

DryingOffEvent has a different name. **DryingOffEvent** vs **icarMilkingDryOffEventResource**

**Message** type is missing in icarDeviceResources. In ADE supportedMessages property refers directly to icarMessageType enum, but in HUB there is a reference to Message type first, then to icarMessageType enum.

**Comment by cookeac** [comment]
Closing - this was due to a time difference between when 1.2 was released and the PR merging the changed items was merged. Will be addressed by releasing 1.3.
