### ISSUE TITLE
Check that exampleURLScheme is complete with resource types for 1.3

### ISSUE THREAD

**Issue by cookeac** [adewg/ICAR#326]
We think this should be deprecated for the future but in version 1.3 it should contain GET for all resource types.

**Comment by erwinspeybroeck** [comment]
in management section  : missing = statistics
in health section : missing = health-status
in milk section : missing = milking-withdrawals
in performance section : missing = type-classifications

other way in example url but not in the registrion url = locations

**Comment by cookeac** [comment]
Resolved by #330
