### ISSUE TITLE
Heat recording - standardise vendor-specific fields and make them extensible

### ISSUE THREAD

**Issue by cookeac** [adewg/ICAR#354]
We noted that icarReproHeatEventResource has vendor-specific fields for:
- heatReportNedapCowControl
- heatReportScrSenseTime
These have similar data and the full set of data could encompass both fields.

We wondered if there are ICAR guidelines for standard values.
We would like to consider making standard and/or extensible fields in future and deprecating these ones.

**Comment by cookeac** [comment]
We agreed that @cvigorsICBF will do some research into values of the vendor parameters to see if there is any obvious opportunity for standardisation.

**Comment by dirbSEGES** [comment]
HI, 
I was attending EuroTier and talk with different vendors of "sensors"" and I got the same thoughs that the ADE standard should have a non-vendor specific ressource for theese kind of data. 
My thoughs is it could be described in 2 resources Attentions(or Alarms) and "Measurements"(raw data). 

Attentions could  be described: 
AnimalCoreEvent
Attention:
   AttentionType: heat, health, calving(parturition or fertility?) ,other (more ?) 
       AlarmValue1: string 
       AlarmValue2: string 
       AlarmValue3: string   

Measurements could be described:
AnimalCoreEvent
Measurement:
    MeasurementsValue: string 
    MeasurementsType: Temperature, Activity, Rumination, Other (it can be difficult to make a list that includes all types) 

Do my thoughts makes sense to you?

**Comment by cookeac** [comment]
A proposal for discussion:
1. Update the existing icarReproHeatEventResource

- [ ] mark as deprecated `heatReportScrSenseTime` and `heatReportNedapCowControl` (removing them would be a breaking change suitable for version 2.0).
- [ ] add `heatProbability` : number - this would be a numeric probability (equivalent to the manufacturer-specific `heatIndex` or `heatChance`, with a defined scale - to be discussed, but either 0-100 or 0-1. I would have used certainty, but this is already used for a simple enumeration.
- [ ] add `commencementDateTime` (`icarDateTimeType`) - this is the predicted head commencement, a match to `expirationDateTime` and is now available from some devices.
- [ ] add `inseminationWindow`[], an array of `icarReproHeatWindowType` - which would contain:
* `startDateTime` - date time start of insemination window (if known) - some devices now provide this.
* `endDateTime` - date time end of insemination window (if known) - replaces manufacturer-specific expirationDateTime or breedingWindow. 
* `semenType` - a string or enumeration (standard, sexed-semen...)

2. Add a, icarDeviceAlertEventResource as @dirbSEGES has suggested. I agree with Ditlev's comments on this. It might be wise to wait until the Sensor Working Group makes its recommendations in this area early in 2023.

**Comment by cvigorsICBF** [comment]
Hi,
Just picking up on @dirbSEGES comment on the non-vendor specific approach. 
I am aware of 5 different API specifications of these sensor providers. 

1. 2 have taken the approach of the 'Attentions' section with the multiple AttentionTypes transferred under that
2. 1 has taken the approach of the 'Event' section with all events listed there, including heats, calvings, inseminations etc. 
3. 2 have taken the approach of a section for each event, e.g a section for heat, a section for calving, with details of the event contained within that. 

(By 'section' I mean that it is either a specific service, or part of a large data object containing all data for the herd);

I need more time to look at what data each spec provides and see if there is much in common.

I do think that it is worthwhile waiting for the Sensor Working group to make its recommendations.

**Comment by cookeac** [comment]
Meeting 2023-03-09:
Agreed to the approach above but to:
* Consult with the main vendors of heat monitoring devices
* Contact the Sensor Working Group

**Comment by cvigorsICBF** [comment]
Some feedback received from a vendor of heat monitoring devices.

- heatLevel - new field with suggested values: "potential", "suspicious" or "In heat"
- heatIndex - The preference here is that there is not a standard scale as the value could be between 3.5 and below 10, in exceptional circumstances, it could be over 10.
- inseminationWindow - Different phases possible here: "Start Breeding Window", "Start Optimum Breeding Window", "End Optimum Breeding Window", "End Breeding Window" 

Further comments: 

- "The only thing I do miss is the duration of the heat alert, this might be something that could be covered within the commencement date and Expiration date. So, for example when the cow is still in Heat, then the expiration date will be the same as the current time now. As soon as the cow is out of heat, the expiration date is older than now. That is something we have right now. "

**Comment by cvigorsICBF** [comment]
Proposed Solution:

Required Fields:
- commencementDateTime - icarDateTimeType
- $ref - icarAnimalEventCoreResource

Optional Fields:

- heatDetectionMethod - icarReproHeatDetectionMethodType - no change
- certainty - expand the icarReproHeatCertaintyType enum to include 'potential'
- visualDetection - no change, (but is the description of icarReproHeatIntensityType correct? It says 'insemination'.)
- expirationDateTime  - icarDateTimeType
- optimumInseminationWindow - an array of icarReproHeatWindowType, which consists of
    - startDateTime - icarDateTimeType
    - endDateTime - icarDateTimeType
- standardHeatProbability - integer (between 1 and 100)
- deviceHeatProbability - integer
- device - icarDeviceReferenceType- no change

**Comment by cookeac** [comment]
Changes agreed:
- Add a string name or type to the window
- Drop the standardHeatProbability for now
