### ISSUE TITLE
"number" or "SetId" added the AnimalSet

### ISSUE THREAD

**Issue by dirbSEGES** [adewg/ICAR#356]
Hi, 

We have a need for a field to handle a number or somekind of prefix for each animalSet, to handle identical Names of animalSet. 
The "Id"  is not suitable  for this, the end-user don´t see this. 

BR

**Comment by cookeac** [comment]
Is there any reason why a prefix cannot be added to the name? It could be maintained separately inside your system, but put into the name when passed through an API.

**Comment by dirbSEGES** [comment]
Yes, this is also how we handle this. But we have a user of the api who is creating an animalSet into our system and they would like to use the prefix from their system.

**Comment by cookeac** [comment]
Proposal - add a `reference` (string) field to `icarAnimalSet` for v1.4. It can be used by parties for any other reference information used to synchronise systems or display to the user.

**Comment by cookeac** [comment]
Agreed that we would do this at the meeting on 12 Jan 2023
