### ISSUE TITLE
Define a generalised carcass observation

### ISSUE THREAD

**Issue by cookeac** [adewg/ICAR#362]
There is an increasing variety of observations and measurements recorded on carcasses, particularly with the advent of visual, ultrasound, and x-ray observation. We propose a generalised way of defining carcass observations, so that a "metric" can be defined and its values recorded. The metric would use an icarIdentiferType to allow different metric schemes. We recommend that a subset of well-known metrics be defined in the ADE specifications.

We propose an `icarCarcassObservationType` as follows (required fields in **bold**). This would then be embedded into a resource that identified the animal, carcass (and side or primal if relevant).

| Attribute | Type | Description |
| --- | --- | --- |
| **metric** | icarCarcassMetricIdentifierType | The metric identifier |
| method | string | The standard method used to determine the value of the metric. |
| qualifier | string | A further qualifier applied to describe the metric. |
| value | number | A quantitative value for the measurement or observation. |
| units | string | The units of the value being measured. UN-CEFACT units SHOULD be used if relevant. |
| qualitativeGrade | string | Not all observations are numeric, or others may have a categorisation such as a Grade (e.g. EUROP). |
| observationStatus | `icarObservationStatusType` | Whether the observation was Measured, Calculated, or the measurement or calculation failed. |
| problemDetail | string | If any problem has occurred with the observation measurement or calculation, this is described here. |

Values of `icarObservationStatusType` enumeration are: Measured, NotMeasured, Calculated, NotCalculated.

Note: If could be conceptually useful to aggregate metric + method + qualifier into a single `icarCarcassMetricType` to indicate that they will go together based on the setup of a particular country and plant. For instance, a country might have a standard for a measurement that has two accepted methods and some qualifiers. Please give feedback on this.

**Comment by erwinspeybroeck** [comment]
One drawback: it's not possible to use an enum for certain observations. This means we need to document that in some way. I don't know a good alternative ...
Or we should create something like icarCarcassObservationTypeNL and icarCarcassObservationTypeNZ with different kind of observations - it would be a list of possible observations - the standard would then just make an example of a possible implementation. Don't know if it is understandable what i mean ... and likely ...

**Comment by cookeac** [comment]
That's right, I intended we would use an IdentifierType for observations, and document the enumeration in the markdown files in the existing "well-known" folder within the specs. For instance, see https://github.com/adewg/ICAR/tree/Develop/well-known
This doesn't quite give the same schema enforcement as an enumeration, but it means we can have a common, documented set of observation types for global use, and for country/region-specific or supply-chain-specific use.

**Comment by cookeac** [comment]
Just realised @erwinspeybroeck you meant an enumeration for the string values in `qualitativeGrade` rather than the `metric`.
I'd propose the same process though - the documentation in well-known should include for a metric:
- The valid values for the `qualifier` attribute if any
- Expected/valid values for `units`
- Range for `value` if expected
- Valid values for `qualitativeGrade` if relevant and known. 

I'd be happy to create a markdown template for this.
