### ISSUE TITLE
Testing patch release 1.3.2 prior to release

### ISSUE THREAD

**Issue by cookeac** [adewg/ICAR#364]
Hi everyone,

As many of you will know, after the release of 1.3 (and the fix to withholding event in 1.3.1) a few more problems were discovered with ADE 1.3. These were:
#353 Problem with icarStatistics
#357 AnyOf causes problem with code generation in icarConsignmentType origin and destination addresses.
We also resolved we needed release notes to explain the discriminator changes in 1.3. (#358). I have put this in a release notes MD and link to it from the main readme. I added some text to explain the fixes above.

We believe we have now addressed the above with commits to the branch https://github.com/adewg/ICAR/tree/RC-for-ADE-1-3-2
We would like to test this promptly so it can be released. If you have access to code generation tools, can you please test this branch and report your results so we can merge the branch into both ADE1 (new release 1.3.2) and back into the Develop branch.

Thanks,
  Andrew.

**Comment by cookeac** [comment]
Adding developers with C# and Java, let me know if you haven't got time.

**Comment by AlexeyHardCode** [comment]
C# code generation looks just as expected: 
![image](https://user-images.githubusercontent.com/92816045/218389859-8987a6f6-ebfe-44ae-ba4c-1541947b9339.png)

Also icaStatisticType model code generation is valid.

**Comment by AndreasSchultzGEA** [comment]
Java-Code for Consignment seems to be ok. 
The code for IcarStatisticType could not be testet, as we don't have implemented this parts so far.

![PostalAdress](https://user-images.githubusercontent.com/79915286/218651014-056f320e-379e-497a-bbf1-669713a0974c.png)
