### ISSUE TITLE
Add Inventory to MedicineRessource? 

### ISSUE THREAD

**Issue by dirbSEGES** [adewg/ICAR#369]
Hi 

I will suggest to add "inventory" to the MedicineRessource. To handle the inventory of medicine in the given location.  (I haven´t been able to find a ressource to handel this?)

add something like: 

"inventory": {
                    "type": "string", --?? maybe number, it can be a negative inventory.
                    "description": "Inventory of the medicine at this actuelly time"
 
and also the unit have to be added: 

"DoseUnits": {
            "$ref": "../enums/uncefactDoseUnitsType.json",
            "description": "Units of measurement in UN/CEFACT 3-letter form"

**Comment by cookeac** [comment]
Meeting 2023-03-09
APIs or messages could be:
* Medicine inventory (on hand)
* Medicine purchases / receipt (new medicine arriving)
* Medicine disposal / loss (medicine removed)
* Medicine stocktake (count and adjust medicines - update quantity on-hand without recording disposal)

Use the medicine definition from icarMedicineResource.

@dirbSEGES please add a comment with some examples of your data.

**Comment by erwinspeybroeck** [comment]
We are using 3 API's:

**GET /locations/{location-scheme}/{location-id}/medicine-inventory**
[MedicineInventory{
id*	idstring
medicineId*	idstring
amountInStock*	amountnumber
amountUnit*	amountUnitstring Enum:
[ CCML, GRAM, OTHER, TABLET, DOSE, PIPETTE, INJECTOR, PIECE, CAPSULE, BOLUS, FLASK, LITER, MILLIGRAM, KILOGRAM ]
locationNumber*	locationNumberstring
}]

**GET /locations/{location-scheme}/{location-id}/medicine-losses**
[MedicineLoss{
id*	idstring
medicineId*	idstring
lossDate*	datestring($date)
amount*	amountnumber
amountUnit	amountUnitstring Enum:
[ CCML, GRAM, OTHER, TABLET, DOSE, PIPETTE, INJECTOR, PIECE, CAPSULE, BOLUS, FLASK, LITER, MILLIGRAM, KILOGRAM ]
locationNumber	locationNumberstring
batchNumber	batchNumberstring
reason	reasonMedicineLossstring Enum:
[ ROUNDING_NEGATIVE, ROUNDING_POSITIVE, BROKEN_BOTTLE, EXPIRATION_DATE, RETURN_VETERINARIAN, OTHER ]
}]

**GET /locations/{location-scheme}/{location-id}/medicine-purchase**
[MedicinePurchase{
id	idstring
medicineId	idstring
amount	amountnumber
amountUnit	amountUnitstring Enum:
[ CCML, GRAM, OTHER, TABLET, DOSE, PIPETTE, INJECTOR, PIECE, CAPSULE, BOLUS, FLASK, LITER, MILLIGRAM, KILOGRAM ]
locationNumber	locationNumberstring
purchaseDate	datestring($date)
}]

**Comment by dirbSEGES** [comment]
Hi 

For medicin inventory we have this, I have highlighted(bold) some fields that I think is relevant in this context. Regarding CalculatedStock, we only do this in present time, It is not available historically.  
{
"$id":"4",
"Id":-816544675,
"**HerdId**":1234,
"MedicationFarmId":1234,
"**MedicationId**":40403,
"PRPId":null,
"**MedicationName**":"BUTOXVET - 7,5 mg/ml",
"**MedicationUnit**":"ml",
"BeginningDate":"2021-01-14T00:00:00+01:00",
"BeginningStock":5000.0,
"StatusDate":null,
"StatusStock":null,
"PeriodConsumption":1680.0,
"PeriodInput":0.0,
"PeriodWaste":0.0,
"PeriodCorrection":0.0,
"**CalculatedStock**":3320.0,
"Remark":null,
"Warning":false,
"SelectTime":"2023-03-13T10:07:38+01:00",
"LastUpdatedBy":null,
"LastUpdatedTime":null,
"LatestTransactionDate":"2021-09-01T00:00:00+02:00",
"MedicationFarm":null
}

For medicin transactions we have this, I have highlighted(bold) some fields that I think is relevant in this context:
{
"$id":"2",
"**Id**":106886703,
"MedicationStatusId":null,
"**HerdId**":1234,
"MedicationFarmId":1234,
"**Medication2Id**":40403,
"PRPId":33,
"**TransactionDate**":"2015-02-05T00:00:00+01:00",
"AnimalId":1008470395,
"**MedicationUseCode**":1, (Consumed, Delivered to the farmer, Ordained, Regulated,Waste)
"**Quantity**":-4.0,
"**MedicationUseText**":"Goldningsbehandling", (this is actually also the reference to the "treatmentId") 
"**AnimalNumber**":1234,
"**TransactionRemark**":null,
"NordicItemNumber":13698,
"MedicationRegistrationFarmId":null,
"**LastUpdatedTime**":"2015-02-05T10:51:32+01:00",
"**LastUpdatedBy**":"DYR52972",
"TreatmentId":4709337
}

**Comment by cookeac** [comment]
## Proposed Approach
1. Define a base `icarInventoryItemType` that carries generic information that applies to many different types of product - for instance, medicine, feed, animal management supplies.
2. Integrate this base `icarInventoryItemType` into existing `icarFeedResource` and `icarMedicineResource` types so that it does not add any additional required fields (not a breaking change, just introduces a few consistent optional fields).
3. Define transactions (based on `icarEventCoreResource`) that operate on `icarInventoryItemType` or equivalent resources (such as medicines). These transactions would contain units and quantity.

It would be possible to define just one `icarInventoryTransactionEventResource` that had a `transactionType` (enumerated value), because receipt (receiving or purchasing an item), disposal, use, stocktake, and items on hand all have a very similar set of fields. This is effectively the **medicineUseCode** in @dirbSEGES's example.
