### ISSUE TITLE
Group feed utilisation/allowance event

### ISSUE THREAD

**Issue by cookeac** [adewg/ICAR#382]
Now that we can support group events, it would be useful to have a group feed utilisation event analogous to the individual animal feed utilisation event.

**Comment by cookeac** [comment]
Proposed fields for an `icarGroupFeedingEventResource` based on `icarGroupEventCoreResource`.
Note that as it is for a group, it is not a feed *intake* - the individual animal intakes are not known, so you cannot convert a group feeding event to a set of individual animal feed intakes.

Proposed fields:
| Attribute | Type | Description |
| --- | --- | --- |
| feedingStartDateTime | icarDateTimeType | The RFC3339 UTC moment the feeding started.  (Note that eventDateTime represents the end of feeding. |
| feedVisitDuration | icarFeedDurationType | The length of time of the feeding. |
| feedPerAnimal | array of icarConsumedFeedType | Gives the feed offered to and consumed per animal (average). |
| rationPerAnimal | array of icarConsumedRationType | Gives the ration offered to and consumed per animal (average). |
| device | icarDeviceReferenceType | Optional information about a device used for the feeding, if relevant. |

**Comment by cookeac** [comment]
Draft PR for review #396. Still to add to the URL schemes.

**Comment by cookeac** [comment]
Suggestion - to identify groups (where we do not have animal identifiers) consider adding `reference` - a string - to the `icarInventoryClassification`.

**Comment by ErikUniformAgri** [comment]
Suggest to add `dryMatterPercentage` to icarConsumedFeedType and icarConsumedRationType

**Comment by cookeac** [comment]
We agreed with adding `dryMatterPercentage`.
We would like to change the way times are managed:
* `eventDateTime` is the time that feed is available to animals (effectively the start date time for animals eating)
* `feedingEndDateTime` (if supplied) is the end time at which animals could consume the feed.

Remove the `feedingStartDateTime` (this is now replaced by `eventDateTime`), and `feedVisitDuration`.
