### ISSUE TITLE
Device Attentions message

### ISSUE THREAD

**Issue by cookeac** [adewg/ICAR#393]
Discussed as a small, generalised start from requirement identified at the ICAR 2023 meeting in Spain
@erwinspeybroeck will add an example

**Comment by erwinspeybroeck** [comment]
[ Attention{
description:	
consideration with a view to action.

id	string
The technical, non-meaningful and unique identification code of an object.

animalId	string
The technical, non-meaningful and unique identification code of an object.

attentionType	 string
Type of attention
Enum:
[ HEALTH, PROLONGED_CALVING, POST_CALVING, EATING, ACTIVITY, WALKING, STANDING_UP, STANDING, LYING_TOO_LONG, LYING_TOO_SHORT, INACTIVITY, RUMINATION ]

attentionGroup	string
Group of attention
Enum:
[ BEHAVIOUR, HEALTH ]

startDateTime	dateTimestring($date-time)
This is a timestamp the event occured. The date instant is represented as 2017-08-23T08:59:35.120Z.

endDateTime	string($date-time)
This is a timestamp the event occured. The date instant is represented as 2017-08-23T08:59:35.120Z.

priority	string
Priority of attention
Enum:
[ NORMAL, URGENT ]

source	string
Source of attention
Enum:
[ NEDAP_AGRI_BV, //, SCR_HEADQUARTERS_SENSETIME, //, SCR_HEADQUARTERS_HEATIME ]

creationDateTime	string($date-time)
the moment of insertion in the database

} ]

**Comment by cookeac** [comment]
So an ICAR ADE equivalent might be based on `icarAnimalEventCoreResource` and contain:

| Attribute | Type | Description |
| --- | --- | --- |
| category | `icarAttentionCategoryType` | A category that would allow filtering of alerts. |
| cause | `icarAttentionCauseType` | The cause of the specific alert. |
| priority | `icarAttentionPriorityType` | The relative priority of the alert. |
| device | icarDeviceReferenceType | Identification or details of the device raising the alert. |

* `icarAttentionCategoryType` - { Behaviour, Environment, Health }
* `icarAttentionCauseType` - { Health, ProlongedCalving, PostCalving, Eating, Activity, Walking, StandingUp, Standing, LyingTooLong, LyingTooShort, Inactivity, Rumination, AnimalTemperature, EnvironmentTemperature, Location, Disturbance }
* `icarAttentionPriorityType` - { Informational, Normal, Urgent }

We might wish to consider the event name - should it be Attention? In English we might express this as Warning or Alert or Alarm or Notification.

**Comment by cookeac** [comment]
Agreed we will ask manufacturers to review

**Comment by tpekeler** [comment]
I aked our partner to have a look into this issue.

The response was:
Looks ok to me, I would like to suggest adding Mastitis and Ketosis to the list of enums.

**Comment by cookeac** [comment]
We reviewed #407 
- Change cause into causes and make it an array with 1 or more elements
- Make category and causes mandatory
Ask for more feedback.

**Comment by cookeac** [comment]
Consider creating a Group Attentions message based on icarGroupEventCoreResource.

**Comment by dirksieben** [comment]
Based on the discussion on 7/09/2023, below multiple suggestions for updating the list.
Including an extra field with alert type: 

- Category: Behavior, Environment, Health
- Cause: Health, ProlongedCalving, PostCalvingRisk, LessEating, Activity, Walking, StandingUp, Standing, LyingTooLong, LyingTooShort, Inactivity, LowerRumination, AnimalTemperature, EnvironmentTemperature, Location, Disturbance, Calving, Lameness, mobilityscore, Bodycondition, No movement, Respiration rate, Heart rate/pulse rate, other
- Priority: Informational, normal, urgent
- alertType: String

**Comment by cookeac** [comment]
The other area we discussed was whether the `icarDiagnosisSeverityType` and `icarDiagnosisStageType` enumerations might be helpful in providing more detail for health alerts.

**Comment by JeroenW1** [comment]
Multiple manufactures also include a health score/index with health attentions. This is an integer, the higher the value the more likely the cow is healthy. The score/index helps the farmer in the decision making. It contains more and other information next to the Attention priority and Severity. Its often used for automatic sorting/drafting of animals with health attentions. 
 
Would it be possible to also add some kind of health score (integer)? Just like for example the deviceHeatProbability in the icarReproHeatEvent the health score is also device or manufacture depended. Manufactures have different algorithms to calculated the score and different scales to indicate the score (0 – 10 / 0 – 100 / etc..) .

**Comment by cookeac** [comment]
In response to the suggestion from @JeroenW1 I would suggest we add `deviceAttentionScore` (integer) to the message, with a description similar to "Provides a manufacturer-specific score related to the alert." This way the score can be used for other than health alerts.

**Comment by cookeac** [comment]
Added further commits to #407 addressing suggestions above from @dirksieben and @JeroenW1

**Comment by cookeac** [comment]
We should add "severity" which would be icarDiagnosisSeverityType (an enumeration).

**Comment by cookeac** [comment]
Closing as this has been merged.
