### ISSUE TITLE
Extend feed inventory transactions to allow feeds to be manufactured or harvested on farm

### ISSUE THREAD

**Issue by cookeac** [adewg/ICAR#422]
The existing `icarFeedTransactionResource` represents a transaction that can be used to track receipt or despatch/disposal of feed inventory items at a location (farm) level. The types of transaction are enumerated in `icarInventoryTransactionKindType` and work for a variety of inventory items including medicine and reproductive materials.
```
[  "Receipt", "Disposal", "OnHand", "StockTake", "Use" ]
```

However, it is possible that livestock feed may be conserved and harvested on farm (for instance, hay, straw, and silage). To support this being visualised through the same feed transaction resource, we could add `"Produce"` to the enumeration as a term for on-farm manufacture or harvest of a feed.

@ErikUniformAgri, @erwinspeybroeck you might have some thoughts on this?
@donwilson-rezare tagged for reference.

**Comment by erwinspeybroeck** [comment]
No problem for me - could also be interpreted as a kind of receipt

**Comment by ErikUniformAgri** [comment]
I do not see any problems. We might need this in the future too

Met vriendelijke groet / with kind regards,

Erik van Deelen
E-mail: ***@***.******@***.***>

________________________________
