### ISSUE TITLE
IcarMovementArrivalEventResource: additional information about former events

### ISSUE THREAD

**Issue by AndreasSchultzGEA** [adewg/ICAR#432]
In our HM-System and at least in one of our partners, there is the request to enter additional information about an arriving animal which has taken place bevor the ArrivalEventDateTime.
[PR](https://github.com/adewg/ICAR/pull/431)

**Comment by cookeac** [comment]
I acknowledge some of this is covered by a lactation, but that this may not be immediately available to the destination farm during a movement. I'm not convinced that the solution is to add these fields to the movement event. We should look at adding them as optional status extensions to `icarAnimalCoreResource`, which is supplied as the `animalDetail` field of the movement.

**Comment by AndreasSchultzGEA** [comment]
Thanks for the feedback. I removed the additional properties from the MovementEvent to AnimalCoreEvent

**Comment by cookeac** [comment]
Recommendation from 2023-11-30:
Define icarAnimalStateType
- Add these 4 properties and the reproductive and lactation status
Add animalCurrentState (an icarAnimalStateType) to the arrival event (optional property)
