### ISSUE TITLE
Second ManagementTag in IcarAnimalCoreResource

### ISSUE THREAD

**Issue by AndreasSchultzGEA** [adewg/ICAR#435]

**Comment by cookeac** [comment]
@erwinspeybroeck wrote as a comment on PR #433 
>I know we have another understanding about the management tag. For me it was the small animal number that the farmer uses in his day to day operations. The respondernumbers could also be added as an alternative identifier, and that is an array. Managementtag could also become an array, but that would be a breaking change. Wondering what others are using and how they look at this.

I agree - additional device identifiers for animals (radio frequency devices tags, ankle or neck or bolus responders) should use the existing alternativeIdentifiers[] array with an appropriate scheme. The managementTag was defined for a short farmer ID.

**Comment by AndreasSchultzGEA** [comment]
ok, when there is a different understanding than others, I'll remove the PR
