### ISSUE TITLE
Add Certified Milk Weight and Total Milk Weight to Milking Visit

### ISSUE THREAD

**Issue by cookeac** [adewg/ICAR#436]
I'm adding this issue to allow discussion of PR #434 added by @AndreasSchultzGEA to allow discussion.
The PR adds two (not required) additional weights - certified milk weight and total milk weight.

Andreas will add an explanation of the purpose for these proposed changes.

**Comment by AndreasSchultzGEA** [comment]
The existing property is (in our case) normally used to transmit the certified milk-amount to a milk-recording organization. But this amount may not contain separated amounts.
On the other side, there are e.g. feeding-calculations which intend to calculate feed for animals on the complete milk-production (including separated amounts) of an animal.
Therefore, at least a second milkingMilkWeight is useful.
In addition, the third milkingMilkWeight may extend the former one containing also pre- and post-milking weights.

**Comment by cookeac** [comment]
We agreed to go back to the milk recording organisations and manufacturers and ask how milking weights (separated, discarded, certified, and total) are represented so we can get the names right.

**Comment by cookeac** [comment]
We discussed on 7 March 2024 and agreed:
- The `milkingMilkWeight` within the existing `icarMilkingVisitResource` should remain the standard, "certified" milk weight that is used in genetic evaluations in line with the ICAR Guidelines.
- `separatedMilkWeight` (for a separated quarter), `discardedMilkWeight` (or similar, for milk discarded during cleaning of the teat), and `totalMilkWeight` (the sum of these and the `milkingMilkWeight`) should be additional attributes
- Our preference was to add these to the array of `milkCharacteristics`.

**Comment by cookeac** [comment]
We also noted that at the moment the `characteristic` property of `icarMilkCharacteristicType` is just a string defined by a description. Really this should be an enumeration. However, this could be a breaking change. We should create the enumerated type, and at the moment just link or reference this from the description of `characteristic`. This would greatly improve documentation.

**Comment by AndreasSchultzGEA** [comment]
We decided to close this item
