### ISSUE TITLE
Add support for milking shifts or batch milking to icarMilkingVisitEventResource

### ISSUE THREAD

**Issue by cookeac** [adewg/ICAR#450]
### Discussed in https://github.com/adewg/ICAR/discussions/446

<div type='discussions-op-text'>

<sup>Originally posted by **jdoemel** March 23, 2024</sup>
Hello, question regarding missing data scheme in the `milking-visits` POST endpoint to indicate a milking shift.  Many dairies have a milking shift that crosses 12am and in this example "milkingStartingDateTime": "2024-03-15T05:40:28.000Z" converted to the dairy's timezone is Mar 15, 2024, 12:40:29 AM.  When this milking visits comes via the POST milking-visits endpoint: this is a real farms "milkingStartingDateTime", where does this milking belong in a herd mgmt software program if there is no shiftNumber being posted with the milking?  Secondly, this real life milking visits was actually for Shift 3 2024-03-14.  So we also need a way to tell the partner accepting the POST not only the shift but also the day the shift belongs to.  
I'd like to start a discussion on adding additional data schemes in the POST milking-visits endpoint.  I could explain better probably 

"shiftNumber"
"milkShiftDate"</div>

**Comment by cookeac** [comment]
The context here is that with batch or shift milking (i.e. not robots), it can be useful to distinguish the shift within a local date.
Two primary drivers:
- Herd improvement - Ability to adjust for variation caused by staffing or process in different milking shifts (potentially important environmental factor if different sets of animals end up in each shift)
- Farm management - ability to organise data in farm management software by shift/batch.

This is related to the discussion on **intervals** in the ICAR milk recording guidelines (section 2), but interval would be a strange term to use in this context.

**Comment by cookeac** [comment]
In discussion 2024-04-10 (depending on your time zone) we agreed on:
- `milkingShiftNumber` numeric
- `milkingShiftLocalStartDate` (date, in local time not UTC)

We will each consider and discuss further in our organisations, and perhaps someone could propose a pull request for review.

**Comment by jdoemel** [comment]
@cookeac I would like to adjust my proposal to use the term `milkingShiftNumber`

**Comment by cookeac** [comment]
@jdoemel I have updated the notes above. Given this is a Milking Visit, its not essential to prefix the attributes with milking, but I understand it will help people to put the shift into context.

**Comment by cookeac** [comment]
Discussed 2024-05-08 - @cookeac to create a PR
