### ISSUE TITLE
expand departure reasons

### ISSUE THREAD

**Issue by erwinspeybroeck** [adewg/ICAR#454]
I would like to add 2 reasons:

"extensorleg" - don't know the right English word

"muscleSpasm"

An extensor leg appears from a few months of age. The Achilles tendon is permanently tightened by muscle spasm. This can worsen to such an extent that the hind leg barely touches the ground. It appears as if the affected leg is shorter than the other.

**Comment by cookeac** [comment]
contractedTendon - extensorLeg
muscleCramp or muscleSpasm

**Comment by cookeac** [comment]
Another possibility would be to add an "extendedDepartureReason" to take local coding, as there are many possible reasons.

**Comment by dirbSEGES** [comment]
I think it´s a good idea to make an extension for local implementation. We are not able to map our reasons one to one with the departureReason. 
Remember also the deathReason in the DeathEventResource. It could also be good with "extentedDeathReason" 

And also in the "ReproDoNotBreed" an "extendedDoNotBreedReason" could fit very well. It is normal to place the reason when the animal is marked as DNB.

**Comment by cookeac** [comment]
Meeting 2024-05-16
- Additional optional fields such as extended (or country/recording system specific) fields **could** be used
- Or the existing `remark` field could be considered.

**Comment by cookeac** [comment]
Agreed we should add an optional extendedReasonCode (scheme+ID) to allow for local departure/death/do-not-breed reasons.

**Comment by dirbSEGES** [comment]
Very good, and can it be described as an array of extendedReasonCode? 

"extendedReasonCode" : [ ]

Farmers often cannot settle for just one reason :-)

**Comment by dirbSEGES** [comment]
Great 👍
