### ISSUE TITLE
Review departure reason list

### ISSUE THREAD

**Issue by cookeac** [adewg/ICAR#455]
We agreed it would be good to pool our departure reason lists and decide on a common master list.
We may still want to have departure kind (how), departure reason (why - main reason for an animal leaving), and an extended or detailed reason.

Raised during discussion on #454 

Please add your lists as comments to this issue.

**Comment by taliahdanzinger** [comment]
I've searched the website but haven't had any luck--is there a list of definitions for the current departure reasons? I'm interested in the specifics on the differences between sale, slaughter, superfluous and other.

**Comment by cvigorsICBF** [comment]
Hopefully this is the list you are looking for.
Taken from https://github.com/adewg/ICAR/blob/Develop/enums/icarDepartureReasonType.json

Age
Superfluous
Slaughter
Sale
Newborn
LegOrClaw
Nutrition
Parturition
Mastitis
Fertility
Health
Production
MilkingAbility
BadType
Behaviour
Other
Unknown

I have compared my own organization's list to this list. Most of what is not on this list are related to specific diseases, e.g. Johnes, BVD, or specific milk recording reasons such as high somatic cell count.

**Comment by cookeac** [comment]
Agreed we should add an optional extendedReasonCode (scheme+ID) to allow for local departure/death/do-not-breed reasons.
