### ISSUE TITLE
Sorting of animals

### ISSUE THREAD

**Issue by AndreasSchultzGEA** [adewg/ICAR#456]
Animals might have to be sorted on a farm.
Sorting in general is about getting animals from one area of a farm to another. 
The way in between has to be managed by the HMS.
Therefore, a sorting-API should 
- deliver the sorting-areas of a location
- deliver the currently active sorting-command for an animal
- allow the inactivation of a sorting-command for an animal
- allow the setting of a new sorting-command for an animal

PR: #457

**Comment by cookeac** [comment]
Outcomes of the discussion 2024-04-18:
- Consider standardising locations and areas as "sites". We could then align the Position observations to match.
- Rename the resource (not event) to `icarAnimalSortingCommandResource`. This could then create a pattern for other commands in future.
- Replace `isPermanent` with `validFrom` (which replaces startdate) and `validTo`. Setting validFrom with the date/time that the command was activated, and leaving validTo blank makes the command permanent until replaced.

**Comment by cookeac** [comment]
Resolved by #457
