### ISSUE TITLE
Add support for feeding costs and feed refusal

### ISSUE THREAD

**Issue by ErikUniformAgri** [adewg/ICAR#458]
Several of our partners would like to have more feed related information:

1, The cost of the ingredient/ration. To be defined if this will be the price per kg/lbs/... or the total cost.
2. The amount of refusal. A pen could be fed 1000 kg of feed, but not all of it could be consumed. Currently we use the weight deliverd to the animals as "feedConsumption". But this actually not what they consumed. Should we substract the refusal from the "feedConsumption"? The refusal is measured as a total, not per ingredient. Some parties are not only interested in what the animals have consumed, but also what is not consumed. Since the refusals also have an impact on the costs

My suggestion: 
- Add a "cost" field to both the entitlement and the consumption. 
- Exclude the refusal amounts from the consumption (proportionally divided)
- Take the refusal into account in the costs of the consumption

**Comment by cookeac** [comment]
2024-04-18 For the cost component we agreed to add a `cost` and `currency` to the `icarConsumedFeedType` and `icarConsumedRationType`. This would not be required and could be filled in by farm management software or feed management software.

**Comment by cookeac** [comment]
A question: is "entitled" "delivered" or just "recommended"?
If it is "delivered", then having "entitled" and "consumed" implies "refused"
If entitled means "recommended" or "planned" then we also need "delivered".

@erwinspeybroeck can you please investigate how this has been used in cases that you know of for `icarFeedIntakeEvent`.

**Comment by cookeac** [comment]
Meeting 2024-05-16 We decided to add an optional "delivered" value.
* `entitled` means recommended OR delivered
* `delivered` means only what was delivered
* `consumed` means what was consumed (i.e. delivered - refused)
