### ISSUE TITLE
Add missing property "EventDateTime" in resource "icarGestationResource"

### ISSUE THREAD

**Issue by MartijnBlom101** [adewg/ICAR#459]
The resource "icarGestationResource" currently lacks property, "EventDateTime", which is essential for accurate tracking of the date on which it is determined that an animal is pregnant.

**Expected Behavior:**
The EventDateTime property should be added to the icarGestationResource schema.
This property should represent the date and time when pregnancy is confirmed or determined.

**Comment by cookeac** [comment]
icarGestationResource is really a reporting resource providing summary information about a gestation (equivalent to an icarLactationResource). For recording pregnancy confirmation as an event, we recommend using the `icarReproPregnancyCheckEventResource`, which does have an `eventDateTime`.

However, I can see the case for adding a `latestPregnancyCheckDate` or similar to the `icarGestationResource`. What do other people think?

**Comment by cookeac** [comment]
We discussed this 2024-04-18 and decided not to add the last pregancy check date, as there may be multiple pregnancy check events. The gestation resource is more of a report or prediction.

We should fix the description of the id which refers to this as an "event".

**Comment by cookeac** [comment]
Closing this issue in favour of #463
