### ISSUE TITLE
Add Animal property to AttentionEventResource

### ISSUE THREAD

**Issue by jdonovan-dml** [adewg/ICAR#461]
For the Attention event, can we include the option to identify the animal by icarAnimalEventCoreResource.json?  Currently it appears that the only way to identify the animal is via the device ID.  This requires the third party to be aware of device -> animal pairing

**Comment by cookeac** [comment]
The `icarAttentionEventResource` (on Develop branch) currently includes "allOf" `icarAnimalEventCoreResource`.
See: [resources/icarAttentionEventResource.json](https://github.com/adewg/ICAR/blob/Develop/resources/icarAttentionEventResource.json)
