### ISSUE TITLE
Sorting command with multiple sorting sites

### ISSUE THREAD

**Issue by JeroenW1** [adewg/ICAR#477]
We are currently implementing the new sorting endpoints. However, we encountered a problem with the scenario that there can be multiple sorting sites for the same sorting command.

In some situations, a milking parlour may have two exits, each with its own sorting gate. Each sorting gate has its own sorting sites. In advance, it is not possible to know through which exit the animal will leave the parlour. Therefore, our system supports the option to select multiple sorting sites for the same sorting command. This means one command is issued, and it is considered completed when the animal is sorted at one of the possible sorting sites.

Would it be possible to change the icarAnimalSortingCommandResource to include a list of sorting sites instead of having only one sorting site?

**Comment by cookeac** [comment]
Agreed to rename "site" to "sites" and make it an array of strings, and release in 1.4.1. It would be a breaking change but noone is yet using this in production.
