### ISSUE TITLE
Heat API

### ISSUE THREAD

**Issue by erwinspeybroeck** [adewg/ICAR#58]
Proposed properties:

- **icarEventCoreResource.json** unique id, aniaml id, location id, event date time
- **HeatDetectionMethod** enumeration : C=Chemical, V=Visual, P=Pedometer, O= Other
- **certainty** enumeration : in heat, suspect
- **expirationDateTime** timestamp on which the heat event expires
- **DeviceSpecific**
- - **Visual**
- - - **heatSign** array : enumeration : Slime, Clear slime, Interested in other animals, Stands under, Bawling, Blood
- - - **heatIntensity** : enumeration : Very weak, Weak, Normal, Strong, Very strong
- - **ScrSenseTime**
- - - **BreedingWindow** :  number of hours to AI
- - - **heatIndex** : indication of the certainty of the heat
- - **NedapCowControl**
- - - **indicationExpirationDateTime** : timestamp the indication expires
- - - **indicationCertainty**
- - - **heatChance**
- **device** Identify the device used. Optional
Use the object as defined for weight:
Derives from icarResourceReferenceType, so that it can have a link to the device resource. Optional
deviceType is a device type registered with the database proposed by the Sensor Working Group. This could be a UUID but we prefer a meaningful string.
serial is an Optional unique serial number of the device itself (or a network ID, if networked?)

**Comment by cookeac** [comment]
Merged in PR #70
