### ISSUE TITLE
Devices API

### ISSUE THREAD

**Issue by erwinspeybroeck** [adewg/ICAR#59]
Proposed properties:

- **id** : unique id on the farm (farmlevel)
- **serial** : an Optional unique serial number of the device itself (or a network ID, e.g. MAC-address, or unique IP-address)
- **name** : device name - set by farmer
- **description** : device description - set by farmer
- **location** : identifier + scheme of the location where the device is located
- **software version** : version of the software on the device
- **hardware version** : version of the hardware of the device
- **isActive** : is the device active at this moment?
- **supportedMessages** : array of enumerated messages
- **manufacturer** subresource
- - **device type** : a device type registered with the database proposed by the Sensor Working Group. This could be a UUID but we prefer a meaningful string.
- - **name** : name of the manufacturer
- - **id** : unique id of the manufacturer - domain name/url  --> lely.com, …
- - **device name** : name of the device given by the manufacturer
- - **device  description** : description of the device
- - **device configuration** : configuration of the device

**Comment by cookeac** [comment]
Merged in PR #70
