### ISSUE TITLE
Enum values naming patter (whitespace, dots)

### ISSUE THREAD

**Issue by ahokkonen** [adewg/ICAR#61]
Should enum array values be normalized to follow same naming patter?
Some enums uses whitespace in naming and other not (also some uses dots or other characters):

Example icarReproInseminationType vs icarArrivalReasonType:

InseminationType uses combined names for enum values ("NaturalService", "RunWithBull") and ArrivalReasonType uses names with whitespace ("Internal Transfer", "Sale Return", "Stud Service Return"). Same applies for icarRecommendationType, icarDepartureKindType etc.

I known this is not a big issue, but shoud it still be alligned with common naming convention? :)

**Comment by cookeac** [comment]
I think it should be standardised before we get to version 1.0 :-) and I lean towards combined, CamelCase. What do others think?

**Comment by erwinspeybroeck** [comment]
I agree : CamelCase

**Comment by ahokkonen** [comment]
I also agree that combined CC would be the best.

**Comment by ahokkonen** [comment]
I can take this on my task list, if no objections? :)

**Comment by cookeac** [comment]
That would be great, thanks
