### ISSUE TITLE
icarResourceCollection unnecessary inheritance from icarResource

### ISSUE THREAD

**Issue by ahokkonen** [adewg/ICAR#62]
Is there any real need to have resource collection (icarResourceCollection.jso) be inherited from icarResource base structure? As I understand MetaData is single resource related entity, but not collection of recources.

**Comment by cookeac** [comment]
I agree, I can think of cases where a collection might be a resource itself with MetaData and ID, but these are special cases. There is no reason why the icarResourceCollection should inherit from icarResource.

**Comment by cookeac** [comment]
I agree, I can think of cases where a collection might be a resource itself with MetaData and ID, but these are special cases. There is no reason why the icarResourceCollection should inherit from icarResource.

**Comment by cookeac** [comment]
Addressed in PR #67; discovered there were a few things to merge so leaving this open until merged in case we modify the PR.

**Comment by cookeac** [comment]
PR #67 is now merged.
