### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by henning-winkelmann** [adewg/ICAR#69]
If links #19 are only optional, do we need a standard for Pagination?

**Comment by cookeac** [comment]
See [icarResourceCollection.view](https://github.com/adewg/ICAR/blob/7f5d1d228d9f12e0cdf377bebf73899d797d02cd/Release%20Candidate%20Messages/icarResourceCollection.json#L6) :

The intention was that in the Swagger:
- single GET requests to a specific resource would return the resource (e.g. icarWeightEventResource)
- collection GET requests would return the relevant collection (e.g. icarWeightEventCollection), which defines pagination (by including icarResourceCollection).

**Comment by henning-winkelmann** [comment]
great, is it planned to take over for all messages for the first release?

**Comment by cookeac** [comment]
Yes, see now issue #73
