### ISSUE TITLE
Call for missing documentation

### ISSUE THREAD

**Issue by alamers** [adewg/ICAR#72]
As we are approaching version 1.0, we should look at the documentation as well. This ticket is mostly a call for missing documentation: what do _you_ think we should add to the docs?

**Comment by alamers** [comment]
We should explain the use of identifiers / schemes and give examples. There is already a first start: https://github.com/adewg/ICAR/blob/master/location-scheme.md

**Comment by alamers** [comment]
As mentioned in the call just now (forget who mentioned it...): we should mention the use of these tickets more prominently so people can engange with the workgroup via this way as well.

**Comment by alamers** [comment]
Suggestion was to have a summary of all available messages on the wiki, with a quick summary and how they relate to each other (e.g. what is the difference between a milking visit and a lactation period). Some descriptions on the messages are in the swagger documentation, but it is not easy to extract those onto the wiki. Maybe this is simply some work that we have to do manually.

**Comment by ahokkonen** [comment]
btw, there are one tool we can try to migrate JSON documentation into easy readable markdown form:

https://github.com/adobe/jsonschema2md

Haven't tried this yet, but I'll give it a chance.

**Comment by ahokkonen** [comment]
> btw, there are one tool we can try to migrate JSON documentation into easy readable markdown form:
> 
> https://github.com/adobe/jsonschema2md
> 
> Haven't tried this yet, but I'll give it a chance.

seems like this tool is not very useful for our case, so I'm agree with @alamers to start doing this work manually, at least at the beginning. I can help with updating docs if I'll get permissions for wiki.

**Comment by cookeac** [comment]
I have created a summary in the Wiki at https://github.com/adewg/ICAR/wiki/Resource-entities.

**Comment by alamers** [comment]
* use of tickets is mentioned on main readme, so that part is done
* added a link to the resources from main readme and added it to pull request https://github.com/adewg/ICAR/pull/123

This pull request closes all open doc issues in this ticket.
