### ISSUE TITLE
Adding collection for all type of events resources

### ISSUE THREAD

**Issue by ahokkonen** [adewg/ICAR#73]
Resource collection messages should be added for all types of event resources (as now we have for icarWeightEventResource - icarWeightEventCollection). This could be assigned on me if no one working on that already.

examples:
_icarReproInseminationEventResource -> icarReproInseminationEventCollection
icarAnimalCoreResource -> icarAnimalCoreCollection
etc._

**Comment by cookeac** [comment]
Yes, that was exactly the intent, and @ahokkonen it would be great if you could make a start on this.
