### ISSUE TITLE
Location information requirement for event

### ISSUE THREAD

**Issue by ahokkonen** [adewg/ICAR#86]
@cookeac @erwinspeybroeck @alamers 

"location" is not set as required for event resources nor for base core resource (icarEventCoreResource). Is this correct or should location information be always mandatory for events?

Another thing is that in some events required undefined fields:

- icarMovementArrivalEventResource.json - requirements refers to nonexisting field "_originLocation_"
- icarMovementDepartureEventResource.json.json - requirements refers to nonexisting field "_destinationLocation_" 

Both "_originLocation_" and "_destinationLocation_" are part of icarConsignmentType and requirement should be declared there I suppose.

**Comment by cookeac** [comment]
As noted, the *originLocation* and *destinationLocation* fields were originally in the movement resources and are now in **icarConsignmentType** and should be removed from the movement resource "required" array.
