### ISSUE TITLE
Animal Health Treatments

### ISSUE THREAD

**Issue by cookeac** [adewg/ICAR#96]
The Integrity Systems (Australia) group of companies worked out a good set of messages for animal health diagnosis, treatment plan, and treatment events based on Jon Massey's Bristol University specification, plus feedback from ICAR ADE members and their own experiences.
I will document this under this Issue and organise a pull request when we are happy.

**Comment by cookeac** [comment]
The original work on animal health treatments within the ICAR ADE framework was undertaken by Jon G Massey from Bristol University and can be found here: https://github.com/biospi/UKVetMedicinesDataStandards

Subsequently, a group of Australian livestock companies reviewed these and other specifications as part of the Integrity Systems animal schema project https://github.com/integritysystemscompany/animal_schema. 

This produced three event resource entities and a medicine type.

| Resource/Type | Description | Extends |
| -------- | ----------- | ------- |
| [iscDiagnosisEventResource.json](https://github.com/integritysystemscompany/animal_schema/blob/master/docs/resources/iscDiagnosisEventResource.md) | Diagnosis of an animal's health issue. | icarEventCoreResource |
| [iscTreatmentEventResource.json](https://github.com/integritysystemscompany/animal_schema/blob/master/docs/resources/iscTreatmentEvent.md) | Treatment of an animal with medicine and/or a procedure. | icarEventCoreResource  |
| [iscTreatmentProgrammeEventResource.json](https://github.com/integritysystemscompany/animal_schema/blob/master/docs/resources/iscTreatmentProgramEventResource.md) | Describes a course of treatments for one or more diagnoses. | icarEventCoreResource  |
| [iscMedicineReferenceType](https://github.com/integritysystemscompany/animal_schema/blob/master/docs/types/iscMedicineReferenceType.md) | Describes a medicine and will allow it to point to a future medicine resource. | - |

I propose that these resources and their corresponding types be changed to prefix with icar instead of isc, and be moved into ADE version 1.1.

**Comment by ghost** [comment]
In the discussion today we came across events that might happen during a treatment. Specifically in Canada, keeping records of broken needles is required.

IMHO, we could add a comment field (however, bad for finding specific events) or add a list/set of events that happend, e.g. also with a type = "broken needle" or similar.

**Comment by erwinspeybroeck** [comment]
Could it be interpreted as a diagnosis event  linked to that treatment?
