### ISSUE TITLE
Conformation Scores

### ISSUE THREAD

**Issue by cookeac** [adewg/ICAR#97]
We have a need to transfer Conformation Scores (recorded by inspectors, following the ICAR guidelines http://www.icar.org/Guidelines/05-Conformation-Recording.pdf) for a project in New Zealand.

I propose to document the proposed messages in this Issue for review and approval, perhaps based on the work done on scores by the Integrity Systems group in Australia as well as the ICAR Guidelines.

**Comment by cookeac** [comment]
Conformation recording of dairy cattle
From https://www.icar.org/Guidelines/05-Conformation-Recording.pdf
Proposal: Support the recording of the standard linear scores from the ICAR guidelines.
This allows non-production traits of cattle to be assessed by qualified persons.
1.	Each score should be an event with the date of scoring as the event date
2.	The person responsible should be identified
3.	The score itself has the values of 1 to 9 numeric
4.	There are several trait names (including body condition score) listed in the ICAR guidelines (part 1.2 for dairy cattle, 2.3 for dual purpose, 3.2 for beef cattle, 4.2 for dairy goats).
While many of the trait names are the same, the precise instructions for scoring might be slightly different for dairy cattle and dual purpose cattle (in theory, although they look mostly the same).
5.	Body condition score, and some other traits (rear teat placement for example) might increasingly be able to be assessed by computer vision or other sensing technologies. What additional fields would be required to cater for this?
6.	This proposal does not include composite or classification grades, where scores are combined to create a percentage scale for an area.
7.	This proposal does not include defect recording (part 6 of the ICAR guideline).

Proposed approach
**icarConformationScoreEventResource**

| Property | Type | Notes |
| -------- | ---- | ----- |
| conformationTrait | enumeration | Create one standard enumeration from the set of trait names. |
| score | numeric 1-9 | Assuming ICAR standard values – some countries use their own scores (e.g. 1-5 with 0.5 increments. |

An alternative would be to define a *Score Reference Type*  that defined the country, species, scheme, and version. This would might need us to remove the validation on *score* because some scoring schemes have very different ranges, and even non-numeric values.
https://github.com/integritysystemscompany/animal_schema/blob/master/docs/types/iscScoreReferenceType.md

**Comment by ahokkonen** [comment]
BCS mentioned in issue #83 shoud be defined as part of this event.

Message format proposed for conformation event:

- **id**: unique id of the event resource _(through base event type)_
- **event date**: date of the score _(through base event type)_
- **animal identifier**: the scheme and the identifier for the animal _(through base event type)_
- **location identifier**: the scheme and the identifier for the location _(through base event type)_
- **trait**: trait name enumeration [stature, chest width, body depth, angularity, etc.]
- **score**: score value
- **method**: scoring method enumeration [manual/visual, automatic] (or if extended [visual, ultrasonic, camera])
- **responsible**: responsible person 
- **device**: equipment/device used for scoring if done by automation_(through base event type)_
- **meta data** _(through base event type)_
- **anything else?**

Should all traits for different cattle purposes (dairy, dual, beed) be combined into one large icarConformationTraitType? Should cattle purpose also be defined in message? 

Draft for JSON implementation:

```json
{
    "description": "Event for recording conformation scores",
  
    "allOf": [{
        "$ref": "../resources/icarEventCoreResource.json"
      },
      {
        "type": "object",
  
        "properties": {
          "score": {
            "type": "integer",
            "description": "Conformation score with values of 1 to 9 numeric"
          },
          "trait": {
            "$ref": "../enums/icarConformationScoreTraitType.json",
            "description": "Conformation trait type according ICAR guidelines"
          },
          "method": {
            "$ref": "../enums/icarConformationScoreMethodType.json",
            "description": "Scoring method"
          },
          "device": {
            "$ref": "../resources/icarDeviceResource.json",
            "description": "Device used for automated scoring"
          }
        }
      }
    ]
  }
```
Could this potentially be a problem when using resource type (device) for defining nested property?
Unwanted fields like id, date, meta will be automatically included.
